In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

# Обработка данных

Краткое описание данных:
* SalePrice - the property's sale price in dollars. This is the target variable that you're trying to predict.
* MSSubClass: The building class
* MSZoning: The general zoning classification
* LotFrontage: Linear feet of street connected to property
* LotArea: Lot size in square feet
* Street: Type of road access
* Alley: Type of alley access
* LotShape: General shape of property
* LandContour: Flatness of the property
* Utilities: Type of utilities available
* LotConfig: Lot configuration
* LandSlope: Slope of property
* Neighborhood: Physical locations within Ames city limits
* Condition1: Proximity to main road or railroad
* Condition2: Proximity to main road or railroad (if a second is present)
* BldgType: Type of dwelling
* HouseStyle: Style of dwelling
* OverallQual: Overall material and finish quality
* OverallCond: Overall condition rating
* YearBuilt: Original construction date
* YearRemodAdd: Remodel date
* RoofStyle: Type of roof
* RoofMatl: Roof material
* Exterior1st: Exterior covering on house
* Exterior2nd: Exterior covering on house (if more than one material)
* MasVnrType: Masonry veneer type
* MasVnrArea: Masonry veneer area in square feet
* ExterQual: Exterior material quality
* ExterCond: Present condition of the material on the exterior
* Foundation: Type of foundation
* BsmtQual: Height of the basement
* BsmtCond: General condition of the basement
* BsmtExposure: Walkout or garden level basement walls
* BsmtFinType1: Quality of basement finished area
* BsmtFinSF1: Type 1 finished square feet
* BsmtFinType2: Quality of second finished area (if present)
* BsmtFinSF2: Type 2 finished square feet
* BsmtUnfSF: Unfinished square feet of basement area
* TotalBsmtSF: Total square feet of basement area
* Heating: Type of heating
* HeatingQC: Heating quality and condition
* CentralAir: Central air conditioning
* Electrical: Electrical system
* 1stFlrSF: First Floor square feet
* 2ndFlrSF: Second floor square feet
* LowQualFinSF: Low quality finished square feet (all floors)
* GrLivArea: Above grade (ground) living area square feet
* BsmtFullBath: Basement full bathrooms
* BsmtHalfBath: Basement half bathrooms
* FullBath: Full bathrooms above grade
* HalfBath: Half baths above grade
* Bedroom: Number of bedrooms above basement level
* Kitchen: Number of kitchens
* KitchenQual: Kitchen quality
* TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)
* Functional: Home functionality rating
* Fireplaces: Number of fireplaces
* FireplaceQu: Fireplace quality
* GarageType: Garage location
* GarageYrBlt: Year garage was built
* GarageFinish: Interior finish of the garage
* GarageCars: Size of garage in car capacity
* GarageArea: Size of garage in square feet
* GarageQual: Garage quality
* GarageCond: Garage condition
* PavedDrive: Paved driveway
* WoodDeckSF: Wood deck area in square feet
* OpenPorchSF: Open porch area in square feet
* EnclosedPorch: Enclosed porch area in square feet
* 3SsnPorch: Three season porch area in square feet
* ScreenPorch: Screen porch area in square feet
* PoolArea: Pool area in square feet
* PoolQC: Pool quality
* Fence: Fence quality
* MiscFeature: Miscellaneous feature not covered in other categories
* MiscVal: $Value of miscellaneous feature
* MoSold: Month Sold
* YrSold: Year Sold
* SaleType: Type of sale
* SaleCondition: Condition of sale

In [2]:
train = pd.read_csv('train_price.csv')
labels = train["SalePrice"]
train = train.drop('SalePrice', axis=1)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(train, labels, test_size=0.33, random_state=142)

In [4]:
nans=pd.isnull(X_train).sum()
nans[nans>0]

LotFrontage     173
Alley           917
MasVnrType      592
MasVnrArea        5
BsmtQual         24
BsmtCond         24
BsmtExposure     25
BsmtFinType1     24
BsmtFinType2     25
Electrical        1
FireplaceQu     464
GarageType       63
GarageYrBlt      63
GarageFinish     63
GarageQual       63
GarageCond       63
PoolQC          975
Fence           799
MiscFeature     945
dtype: int64

In [5]:
X_train=X_train.drop(["Id","Alley", "Fence", "MiscFeature", "PoolQC", "FireplaceQu"], axis=1)
X_test=X_test.drop(["Id","Alley", "Fence", "MiscFeature", "PoolQC", "FireplaceQu"], axis=1)

In [6]:
all_columns = X_train.columns.values
non_categorical = ["LotFrontage", "LotArea", "MasVnrArea", "BsmtFinSF1", 
                   "BsmtFinSF2", "BsmtUnfSF", "TotalBsmtSF", "1stFlrSF", 
                   "2ndFlrSF", "LowQualFinSF", "GrLivArea", "GarageArea", 
                   "WoodDeckSF", "OpenPorchSF", "EnclosedPorch", "3SsnPorch", 
                   "ScreenPorch","PoolArea", "MiscVal"]

catigorial = [value for value in all_columns if value not in non_categorical]

In [7]:
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(X_train[catigorial])

features_name = enc.get_feature_names_out(catigorial)
X_train[features_name] =  enc.transform(X_train[catigorial]).toarray()
X_train = X_train.drop(catigorial, axis=1)

X_test[features_name] = enc.transform(X_test[catigorial]).toarray()
X_test = X_test.drop(catigorial, axis=1)
print(features_name)

C:\Users\eldo7\AppData\Local\Temp\ipykernel_10888\953044231.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X_train[features_name] =  enc.transform(X_train[catigorial]).toarray()
C:\Users\eldo7\AppData\Local\Temp\ipykernel_10888\953044231.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X_test[features_name] = enc.transform(X_test[catigorial]).toarray()

['MSSubClass_20' 'MSSubClass_30' 'MSSubClass_40' 'MSSubClass_45'
 'MSSubClass_50' 'MSSubClass_60' 'MSSubClass_70' 'MSSubClass_75'
 'MSSubClass_80' 'MSSubClass_85' 'MSSubClass_90' 'MSSubClass_120'
 'MSSubClass_160' 'MSSubClass_180' 'MSSubClass_190' 'MSZoning_C (all)'
 'MSZoning_FV' 'MSZoning_RH' 'MSZoning_RL' 'MSZoning_RM' 'Street_Grvl'
 'Street_Pave' 'LotShape_IR1' 'LotShape_IR2' 'LotShape_IR3' 'LotShape_Reg'
 'LandContour_Bnk' 'LandContour_HLS' 'LandContour_Low' 'LandContour_Lvl'
 'Utilities_AllPub' 'Utilities_NoSeWa' 'LotConfig_Corner'
 'LotConfig_CulDSac' 'LotConfig_FR2' 'LotConfig_FR3' 'LotConfig_Inside'
 'LandSlope_Gtl' 'LandSlope_Mod' 'LandSlope_Sev' 'Neighborhood_Blmngtn'
 'Neighborhood_Blueste' 'Neighborhood_BrDale' 'Neighborhood_BrkSide'
 'Neighborhood_ClearCr' 'Neighborhood_CollgCr' 'Neighborhood_Crawfor'
 'Neighborhood_Edwards' 'Neighborhood_Gilbert' 'Neighborhood_IDOTRR'
 'Neighborhood_MeadowV' 'Neighborhood_Mitchel' 'Neighborhood_NAmes'
 'Neighborhood_NPkVill' 'Neighborhood_NWAmes' 'Neighborhood_NoRidge'
 'Neighborhood_NridgHt' 'Neighborhood_OldTown' 'Neighborhood_SWISU'
 'Neighborhood_Sawyer' 'Neighborhood_SawyerW' 'Neighborhood_Somerst'
 'Neighborhood_StoneBr' 'Neighborhood_Timber' 'Neighborhood_Veenker'
 'Condition1_Artery' 'Condition1_Feedr' 'Condition1_Norm'
 'Condition1_PosA' 'Condition1_PosN' 'Condition1_RRAe' 'Condition1_RRAn'
 'Condition1_RRNe' 'Condition1_RRNn' 'Condition2_Artery'
 'Condition2_Feedr' 'Condition2_Norm' 'Condition2_PosN' 'Condition2_RRAn'
 'BldgType_1Fam' 'BldgType_2fmCon' 'BldgType_Duplex' 'BldgType_Twnhs'
 'BldgType_TwnhsE' 'HouseStyle_1.5Fin' 'HouseStyle_1.5Unf'
 'HouseStyle_1Story' 'HouseStyle_2.5Fin' 'HouseStyle_2.5Unf'
 'HouseStyle_2Story' 'HouseStyle_SFoyer' 'HouseStyle_SLvl' 'OverallQual_1'
 'OverallQual_2' 'OverallQual_3' 'OverallQual_4' 'OverallQual_5'
 'OverallQual_6' 'OverallQual_7' 'OverallQual_8' 'OverallQual_9'
 'OverallQual_10' 'OverallCond_2' 'OverallCond_3' 'OverallCond_4'
 'OverallCond_5' 'OverallCond_6' 'OverallCond_7' 'OverallCond_8'
 'OverallCond_9' 'YearBuilt_1875' 'YearBuilt_1880' 'YearBuilt_1882'
 'YearBuilt_1885' 'YearBuilt_1890' 'YearBuilt_1892' 'YearBuilt_1898'
 'YearBuilt_1900' 'YearBuilt_1904' 'YearBuilt_1905' 'YearBuilt_1906'
 'YearBuilt_1908' 'YearBuilt_1910' 'YearBuilt_1911' 'YearBuilt_1912'
 'YearBuilt_1913' 'YearBuilt_1914' 'YearBuilt_1915' 'YearBuilt_1916'
 'YearBuilt_1917' 'YearBuilt_1918' 'YearBuilt_1919' 'YearBuilt_1920'
 'YearBuilt_1921' 'YearBuilt_1922' 'YearBuilt_1923' 'YearBuilt_1924'
 'YearBuilt_1925' 'YearBuilt_1926' 'YearBuilt_1927' 'YearBuilt_1928'
 'YearBuilt_1929' 'YearBuilt_1930' 'YearBuilt_1931' 'YearBuilt_1934'
 'YearBuilt_1935' 'YearBuilt_1936' 'YearBuilt_1937' 'YearBuilt_1938'
 'YearBuilt_1939' 'YearBuilt_1940' 'YearBuilt_1941' 'YearBuilt_1942'
 'YearBuilt_1945' 'YearBuilt_1946' 'YearBuilt_1947' 'YearBuilt_1948'
 'YearBuilt_1949' 'YearBuilt_1950' 'YearBuilt_1951' 'YearBuilt_1952'
 'YearBuilt_1953' 'YearBuilt_1954' 'YearBuilt_1955' 'YearBuilt_1956'
 'YearBuilt_1957' 'YearBuilt_1958' 'YearBuilt_1959' 'YearBuilt_1960'
 'YearBuilt_1961' 'YearBuilt_1962' 'YearBuilt_1963' 'YearBuilt_1964'
 'YearBuilt_1965' 'YearBuilt_1966' 'YearBuilt_1967' 'YearBuilt_1968'
 'YearBuilt_1969' 'YearBuilt_1970' 'YearBuilt_1971' 'YearBuilt_1972'
 'YearBuilt_1973' 'YearBuilt_1974' 'YearBuilt_1975' 'YearBuilt_1976'
 'YearBuilt_1977' 'YearBuilt_1978' 'YearBuilt_1979' 'YearBuilt_1980'
 'YearBuilt_1981' 'YearBuilt_1982' 'YearBuilt_1983' 'YearBuilt_1984'
 'YearBuilt_1985' 'YearBuilt_1986' 'YearBuilt_1987' 'YearBuilt_1988'
 'YearBuilt_1989' 'YearBuilt_1990' 'YearBuilt_1991' 'YearBuilt_1992'
 'YearBuilt_1993' 'YearBuilt_1994' 'YearBuilt_1995' 'YearBuilt_1996'
 'YearBuilt_1997' 'YearBuilt_1998' 'YearBuilt_1999' 'YearBuilt_2000'
 'YearBuilt_2001' 'YearBuilt_2002' 'YearBuilt_2003' 'YearBuilt_2004'
 'YearBuilt_2005' 'YearBuilt_2006' 'YearBuilt_2007' 'YearBuilt_2008'
 'YearBuilt_2009' 'YearBuilt_2010' 'YearRemodAdd_1950' 'YearRemodAdd_1951'
 'YearRemodAdd_1952' 'YearRemodAdd_1953' 'YearRemodAdd_1954'
 'YearRemodAdd_1955' 'YearRemodAdd_1956' 'YearRemodAdd_1957'
 'YearRemodAdd_1958' 'YearRemodAdd_1959' 'YearRemodAdd_1960'
 'YearRemodAdd_1961' 'YearRemodAdd_1962' 'YearRemodAdd_1963'
 'YearRemodAdd_1964' 'YearRemodAdd_1965' 'YearRemodAdd_1966'
 'YearRemodAdd_1967' 'YearRemodAdd_1968' 'YearRemodAdd_1969'
 'YearRemodAdd_1970' 'YearRemodAdd_1971' 'YearRemodAdd_1972'
 'YearRemodAdd_1973' 'YearRemodAdd_1974' 'YearRemodAdd_1975'
 'YearRemodAdd_1976' 'YearRemodAdd_1977' 'YearRemodAdd_1978'
 'YearRemodAdd_1979' 'YearRemodAdd_1980' 'YearRemodAdd_1981'
 'YearRemodAdd_1982' 'YearRemodAdd_1983' 'YearRemodAdd_1984'
 'YearRemodAdd_1985' 'YearRemodAdd_1986' 'YearRemodAdd_1987'
 'YearRemodAdd_1988' 'YearRemodAdd_1989' 'YearRemodAdd_1990'
 'YearRemodAdd_1991' 'YearRemodAdd_1992' 'YearRemodAdd_1993'
 'YearRemodAdd_1994' 'YearRemodAdd_1995' 'YearRemodAdd_1996'
 'YearRemodAdd_1997' 'YearRemodAdd_1998' 'YearRemodAdd_1999'
 'YearRemodAdd_2000' 'YearRemodAdd_2001' 'YearRemodAdd_2002'
 'YearRemodAdd_2003' 'YearRemodAdd_2004' 'YearRemodAdd_2005'
 'YearRemodAdd_2006' 'YearRemodAdd_2007' 'YearRemodAdd_2008'
 'YearRemodAdd_2009' 'YearRemodAdd_2010' 'RoofStyle_Flat'
 'RoofStyle_Gable' 'RoofStyle_Gambrel' 'RoofStyle_Hip' 'RoofStyle_Mansard'
 'RoofStyle_Shed' 'RoofMatl_ClyTile' 'RoofMatl_CompShg' 'RoofMatl_Roll'
 'RoofMatl_Tar&Grv' 'RoofMatl_WdShake' 'RoofMatl_WdShngl'
 'Exterior1st_AsbShng' 'Exterior1st_BrkComm' 'Exterior1st_BrkFace'
 'Exterior1st_CemntBd' 'Exterior1st_HdBoard' 'Exterior1st_ImStucc'
 'Exterior1st_MetalSd' 'Exterior1st_Plywood' 'Exterior1st_Stone'
 'Exterior1st_Stucco' 'Exterior1st_VinylSd' 'Exterior1st_Wd Sdng'
 'Exterior1st_WdShing' 'Exterior2nd_AsbShng' 'Exterior2nd_Brk Cmn'
 'Exterior2nd_BrkFace' 'Exterior2nd_CmentBd' 'Exterior2nd_HdBoard'
 'Exterior2nd_ImStucc' 'Exterior2nd_MetalSd' 'Exterior2nd_Other'
 'Exterior2nd_Plywood' 'Exterior2nd_Stone' 'Exterior2nd_Stucco'
 'Exterior2nd_VinylSd' 'Exterior2nd_Wd Sdng' 'Exterior2nd_Wd Shng'
 'MasVnrType_BrkCmn' 'MasVnrType_BrkFace' 'MasVnrType_Stone'
 'MasVnrType_nan' 'ExterQual_Ex' 'ExterQual_Fa' 'ExterQual_Gd'
 'ExterQual_TA' 'ExterCond_Ex' 'ExterCond_Fa' 'ExterCond_Gd'
 'ExterCond_TA' 'Foundation_BrkTil' 'Foundation_CBlock' 'Foundation_PConc'
 'Foundation_Slab' 'Foundation_Stone' 'Foundation_Wood' 'BsmtQual_Ex'
 'BsmtQual_Fa' 'BsmtQual_Gd' 'BsmtQual_TA' 'BsmtQual_nan' 'BsmtCond_Fa'
 'BsmtCond_Gd' 'BsmtCond_TA' 'BsmtCond_nan' 'BsmtExposure_Av'
 'BsmtExposure_Gd' 'BsmtExposure_Mn' 'BsmtExposure_No' 'BsmtExposure_nan'
 'BsmtFinType1_ALQ' 'BsmtFinType1_BLQ' 'BsmtFinType1_GLQ'
 'BsmtFinType1_LwQ' 'BsmtFinType1_Rec' 'BsmtFinType1_Unf'
 'BsmtFinType1_nan' 'BsmtFinType2_ALQ' 'BsmtFinType2_BLQ'
 'BsmtFinType2_GLQ' 'BsmtFinType2_LwQ' 'BsmtFinType2_Rec'
 'BsmtFinType2_Unf' 'BsmtFinType2_nan' 'Heating_Floor' 'Heating_GasA'
 'Heating_GasW' 'Heating_Grav' 'Heating_OthW' 'Heating_Wall'
 'HeatingQC_Ex' 'HeatingQC_Fa' 'HeatingQC_Gd' 'HeatingQC_Po'
 'HeatingQC_TA' 'CentralAir_N' 'CentralAir_Y' 'Electrical_FuseA'
 'Electrical_FuseF' 'Electrical_FuseP' 'Electrical_SBrkr' 'Electrical_nan'
 'BsmtFullBath_0' 'BsmtFullBath_1' 'BsmtFullBath_2' 'BsmtFullBath_3'
 'BsmtHalfBath_0' 'BsmtHalfBath_1' 'BsmtHalfBath_2' 'FullBath_0'
 'FullBath_1' 'FullBath_2' 'FullBath_3' 'HalfBath_0' 'HalfBath_1'
 'HalfBath_2' 'BedroomAbvGr_0' 'BedroomAbvGr_1' 'BedroomAbvGr_2'
 'BedroomAbvGr_3' 'BedroomAbvGr_4' 'BedroomAbvGr_5' 'BedroomAbvGr_6'
 'BedroomAbvGr_8' 'KitchenAbvGr_0' 'KitchenAbvGr_1' 'KitchenAbvGr_2'
 'KitchenAbvGr_3' 'KitchenQual_Ex' 'KitchenQual_Fa' 'KitchenQual_Gd'
 'KitchenQual_TA' 'TotRmsAbvGrd_2' 'TotRmsAbvGrd_3' 'TotRmsAbvGrd_4'
 'TotRmsAbvGrd_5' 'TotRmsAbvGrd_6' 'TotRmsAbvGrd_7' 'TotRmsAbvGrd_8'
 'TotRmsAbvGrd_9' 'TotRmsAbvGrd_10' 'TotRmsAbvGrd_11' 'TotRmsAbvGrd_12'
 'TotRmsAbvGrd_14' 'Functional_Maj1' 'Functional_Maj2' 'Functional_Min1'
 'Functional_Min2' 'Functional_Mod' 'Functional_Sev' 'Functional_Typ'
 'Fireplaces_0' 'Fireplaces_1' 'Fireplaces_2' 'Fireplaces_3'
 'GarageType_2Types' 'GarageType_Attchd' 'GarageType_Basment'
 'GarageType_BuiltIn' 'GarageType_CarPort' 'GarageType_Detchd'
 'GarageType_nan' 'GarageYrBlt_1900.0' 'GarageYrBlt_1906.0'
 'GarageYrBlt_1908.0' 'GarageYrBlt_1910.0' 'GarageYrBlt_1914.0'
 'GarageYrBlt_1915.0' 'GarageYrBlt_1916.0' 'GarageYrBlt_1918.0'
 'GarageYrBlt_1920.0' 'GarageYrBlt_1921.0' 'GarageYrBlt_1922.0'
 'GarageYrBlt_1923.0' 'GarageYrBlt_1924.0' 'GarageYrBlt_1925.0'
 'GarageYrBlt_1926.0' 'GarageYrBlt_1927.0' 'GarageYrBlt_1928.0'
 'GarageYrBlt_1929.0' 'GarageYrBlt_1930.0' 'GarageYrBlt_1931.0'
 'GarageYrBlt_1932.0' 'GarageYrBlt_1933.0' 'GarageYrBlt_1934.0'
 'GarageYrBlt_1935.0' 'GarageYrBlt_1936.0' 'GarageYrBlt_1937.0'
 'GarageYrBlt_1939.0' 'GarageYrBlt_1940.0' 'GarageYrBlt_1941.0'
 'GarageYrBlt_1942.0' 'GarageYrBlt_1945.0' 'GarageYrBlt_1946.0'
 'GarageYrBlt_1948.0' 'GarageYrBlt_1949.0' 'GarageYrBlt_1950.0'
 'GarageYrBlt_1951.0' 'GarageYrBlt_1952.0' 'GarageYrBlt_1953.0'
 'GarageYrBlt_1954.0' 'GarageYrBlt_1955.0' 'GarageYrBlt_1956.0'
 'GarageYrBlt_1957.0' 'GarageYrBlt_1958.0' 'GarageYrBlt_1959.0'
 'GarageYrBlt_1960.0' 'GarageYrBlt_1961.0' 'GarageYrBlt_1962.0'
 'GarageYrBlt_1963.0' 'GarageYrBlt_1964.0' 'GarageYrBlt_1965.0'
 'GarageYrBlt_1966.0' 'GarageYrBlt_1967.0' 'GarageYrBlt_1968.0'
 'GarageYrBlt_1969.0' 'GarageYrBlt_1970.0' 'GarageYrBlt_1971.0'
 'GarageYrBlt_1972.0' 'GarageYrBlt_1973.0' 'GarageYrBlt_1974.0'
 'GarageYrBlt_1975.0' 'GarageYrBlt_1976.0' 'GarageYrBlt_1977.0'
 'GarageYrBlt_1978.0' 'GarageYrBlt_1979.0' 'GarageYrBlt_1980.0'
 'GarageYrBlt_1981.0' 'GarageYrBlt_1982.0' 'GarageYrBlt_1983.0'
 'GarageYrBlt_1984.0' 'GarageYrBlt_1985.0' 'GarageYrBlt_1986.0'
 'GarageYrBlt_1987.0' 'GarageYrBlt_1988.0' 'GarageYrBlt_1989.0'
 'GarageYrBlt_1990.0' 'GarageYrBlt_1991.0' 'GarageYrBlt_1992.0'
 'GarageYrBlt_1993.0' 'GarageYrBlt_1994.0' 'GarageYrBlt_1995.0'
 'GarageYrBlt_1996.0' 'GarageYrBlt_1997.0' 'GarageYrBlt_1998.0'
 'GarageYrBlt_1999.0' 'GarageYrBlt_2000.0' 'GarageYrBlt_2001.0'
 'GarageYrBlt_2002.0' 'GarageYrBlt_2003.0' 'GarageYrBlt_2004.0'
 'GarageYrBlt_2005.0' 'GarageYrBlt_2006.0' 'GarageYrBlt_2007.0'
 'GarageYrBlt_2008.0' 'GarageYrBlt_2009.0' 'GarageYrBlt_2010.0'
 'GarageYrBlt_nan' 'GarageFinish_Fin' 'GarageFinish_RFn'
 'GarageFinish_Unf' 'GarageFinish_nan' 'GarageCars_0' 'GarageCars_1'
 'GarageCars_2' 'GarageCars_3' 'GarageCars_4' 'GarageQual_Ex'
 'GarageQual_Fa' 'GarageQual_Gd' 'GarageQual_Po' 'GarageQual_TA'
 'GarageQual_nan' 'GarageCond_Ex' 'GarageCond_Fa' 'GarageCond_Gd'
 'GarageCond_Po' 'GarageCond_TA' 'GarageCond_nan' 'PavedDrive_N'
 'PavedDrive_P' 'PavedDrive_Y' 'MoSold_1' 'MoSold_2' 'MoSold_3' 'MoSold_4'
 'MoSold_5' 'MoSold_6' 'MoSold_7' 'MoSold_8' 'MoSold_9' 'MoSold_10'
 'MoSold_11' 'MoSold_12' 'YrSold_2006' 'YrSold_2007' 'YrSold_2008'
 'YrSold_2009' 'YrSold_2010' 'SaleType_COD' 'SaleType_CWD' 'SaleType_Con'
 'SaleType_ConLD' 'SaleType_ConLI' 'SaleType_ConLw' 'SaleType_New'
 'SaleType_Oth' 'SaleType_WD' 'SaleCondition_Abnorml'
 'SaleCondition_AdjLand' 'SaleCondition_Alloca' 'SaleCondition_Family'
 'SaleCondition_Normal' 'SaleCondition_Partial']

In [8]:
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
X_train = imp.fit_transform(X_train)
X_test = imp.transform(X_test)

In [9]:
X_train_clear, X_test_clear = X_train, X_test

# Sklearn

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
model = LinearRegression()
model.fit(X_train_clear, y_train)
print(f"R2 на train: {model.score(X_train_clear, y_train)}")
print(f"R2 на test: {model.score(X_test_clear, y_test)}")

R2 на train: 0.9686156902618233
R2 на test: 0.6521199438990353

In [12]:
pca = PCA(whiten=True)
pca.fit(X_train)
variance = pd.DataFrame(pca.explained_variance_ratio_)
np.cumsum(pca.explained_variance_ratio_)

array([0.03572396, 0.0544179 , 0.0693919 , 0.08300038, 0.09620454,
       0.10825926, 0.11833344, 0.1278904 , 0.13647934, 0.14487536,
       0.15263502, 0.16013307, 0.16733551, 0.17423849, 0.1810798 ,
       0.18769729, 0.19428796, 0.20072651, 0.20706908, 0.21329527,
       0.21946153, 0.22558031, 0.23163863, 0.23756624, 0.24346707,
       0.24923681, 0.25496191, 0.26062101, 0.26619557, 0.27173594,
       0.27721081, 0.28263934, 0.28803771, 0.29337935, 0.29866513,
       0.30390255, 0.30910821, 0.31428902, 0.31941817, 0.32445807,
       0.32949511, 0.33447658, 0.33942826, 0.34434951, 0.34924339,
       0.35410933, 0.35889738, 0.36366626, 0.36840056, 0.37312894,
       0.37780013, 0.38246219, 0.38711552, 0.39174386, 0.39632969,
       0.40088631, 0.40542406, 0.40993305, 0.41441793, 0.41889081,
       0.42333665, 0.42776302, 0.43214578, 0.43649529, 0.44082664,
       0.44512242, 0.44939856, 0.45366378, 0.4579062 , 0.462118  ,
       0.46631246, 0.47046225, 0.47459704, 0.47867818, 0.48275314,
       0.48679933, 0.49082867, 0.49480476, 0.4987584 , 0.50269158,
       0.50660356, 0.51048802, 0.51433444, 0.51816957, 0.5219837 ,
       0.52575481, 0.52951283, 0.53324539, 0.53695659, 0.54063507,
       0.54428737, 0.54792778, 0.55154931, 0.55512558, 0.55868154,
       0.56219781, 0.56567831, 0.56912522, 0.57256072, 0.57598617,
       0.5793967 , 0.58277884, 0.58614593, 0.58947986, 0.59279637,
       0.5960934 , 0.59933707, 0.60256699, 0.6057904 , 0.60898202,
       0.61217255, 0.61532837, 0.61846729, 0.62157685, 0.62466547,
       0.62773931, 0.63080158, 0.63383428, 0.63684746, 0.63983858,
       0.64282338, 0.64578453, 0.64872016, 0.65162996, 0.65452935,
       0.65739459, 0.66023812, 0.66305961, 0.66585825, 0.66864593,
       0.67140041, 0.6741352 , 0.67685404, 0.67955228, 0.68222549,
       0.68488814, 0.6875358 , 0.69015786, 0.69276647, 0.6953587 ,
       0.69792984, 0.70047702, 0.70300056, 0.70551253, 0.70801892,
       0.71050093, 0.7129706 , 0.71541766, 0.71784769, 0.7202563 ,
       0.72264927, 0.72502793, 0.72738417, 0.72972079, 0.73204414,
       0.73433989, 0.73662976, 0.73889368, 0.74111965, 0.74332955,
       0.74553534, 0.74772224, 0.74990159, 0.75205233, 0.75418506,
       0.75629887, 0.75840559, 0.76049578, 0.76257998, 0.76465309,
       0.7666896 , 0.76871125, 0.77071831, 0.77270997, 0.77469571,
       0.77666532, 0.77863038, 0.78057177, 0.78250195, 0.78441774,
       0.78632992, 0.78821669, 0.79009209, 0.79195984, 0.79381318,
       0.79565628, 0.79748605, 0.79930159, 0.80110877, 0.80287571,
       0.80463964, 0.80638979, 0.80812888, 0.80985441, 0.81157267,
       0.81327801, 0.81496733, 0.81664924, 0.81831585, 0.81997184,
       0.82162034, 0.82326116, 0.82487174, 0.82647446, 0.82807356,
       0.82965265, 0.83122235, 0.83278928, 0.83434859, 0.83589125,
       0.83742693, 0.83895963, 0.84048126, 0.84198823, 0.8434807 ,
       0.84496104, 0.84643792, 0.84789827, 0.84934843, 0.85078802,
       0.8522226 , 0.85364518, 0.85505598, 0.85644937, 0.85782974,
       0.85920758, 0.86057949, 0.86194683, 0.86329769, 0.86464   ,
       0.86596789, 0.86728267, 0.86858661, 0.86988039, 0.87116775,
       0.87244046, 0.87370473, 0.8749665 , 0.8762182 , 0.87745457,
       0.87868534, 0.87990287, 0.88111178, 0.88231536, 0.88350278,
       0.88467725, 0.88584634, 0.887     , 0.88814468, 0.88928463,
       0.89041723, 0.89153743, 0.89265481, 0.89375812, 0.89485415,
       0.89593956, 0.89701989, 0.89809165, 0.89915971, 0.90021943,
       0.901275  , 0.90231096, 0.90333761, 0.90436152, 0.90537727,
       0.9063844 , 0.90737979, 0.9083694 , 0.90934686, 0.91032096,
       0.91128584, 0.91224426, 0.91319745, 0.91413894, 0.91506918,
       0.91599274, 0.91691165, 0.91782348, 0.91872745, 0.91962696,
       0.92052387, 0.92140231, 0.92227574, 0.92314644, 0.92400784,
       0.92486555, 0.92572138, 0.92655914, 0.92739526, 0.92822123,
       0.92904246, 0.92985604, 0.93066746, 0.93146008, 0.93224854,
       0.93303547, 0.93381355, 0.93458622, 0.9353552 , 0.93611632,
       0.93687113, 0.93762049, 0.9383575 , 0.9390903 , 0.93981488,
       0.9405347 , 0.94124755, 0.94195764, 0.94266248, 0.94335836,
       0.94404427, 0.94472561, 0.94540514, 0.9460741 , 0.94673778,
       0.94739685, 0.94805278, 0.94870178, 0.9493431 , 0.9499822 ,
       0.95060929, 0.95123289, 0.95185136, 0.95246227, 0.95306952,
       0.95367116, 0.95426843, 0.95485849, 0.9554362 , 0.956009  ,
       0.95657752, 0.95714026, 0.95769745, 0.95825324, 0.95880202,
       0.95935022, 0.95989277, 0.9604269 , 0.9609548 , 0.96147694,
       0.96199707, 0.96251411, 0.96302607, 0.96353048, 0.96403151,
       0.96452926, 0.96502198, 0.96551192, 0.96599804, 0.96647694,
       0.96694913, 0.96741877, 0.96788553, 0.96834709, 0.96879916,
       0.96924806, 0.96969386, 0.97013578, 0.97057265, 0.97100485,
       0.97143128, 0.97185235, 0.97227245, 0.97268327, 0.9730927 ,
       0.97349717, 0.97389607, 0.97429333, 0.97468543, 0.97507086,
       0.97545234, 0.97582655, 0.97619917, 0.97656887, 0.97693744,
       0.97730344, 0.97766565, 0.97802412, 0.97837908, 0.9787254 ,
       0.97907077, 0.97941337, 0.97975058, 0.98008425, 0.98041318,
       0.98073801, 0.98105995, 0.98137597, 0.9816871 , 0.98199509,
       0.98229965, 0.98259825, 0.98289275, 0.9831862 , 0.98347697,
       0.98376422, 0.98404786, 0.98432638, 0.98460148, 0.98487491,
       0.98514593, 0.9854112 , 0.98567523, 0.98593271, 0.98618534,
       0.98643686, 0.98668619, 0.9869314 , 0.98717561, 0.98741588,
       0.98765417, 0.98788839, 0.9881189 , 0.98834844, 0.98857338,
       0.98879766, 0.98901811, 0.98923676, 0.98945367, 0.98966598,
       0.98987478, 0.99008182, 0.99028495, 0.99048498, 0.99068161,
       0.99087688, 0.99107005, 0.99126036, 0.99144763, 0.99163398,
       0.99181672, 0.9919959 , 0.9921731 , 0.99234717, 0.99251931,
       0.99268773, 0.99285404, 0.99301835, 0.99318039, 0.99334086,
       0.99349778, 0.9936515 , 0.9938008 , 0.99394906, 0.99409628,
       0.9942414 , 0.99438547, 0.99452445, 0.9946623 , 0.99479831,
       0.99493171, 0.99506415, 0.99519394, 0.99532095, 0.99544611,
       0.9955695 , 0.99568991, 0.995809  , 0.99592523, 0.99603906,
       0.99614893, 0.99625748, 0.99636516, 0.99647067, 0.99657516,
       0.99667731, 0.99677711, 0.99687557, 0.9969716 , 0.99706448,
       0.99715629, 0.99724667, 0.99733495, 0.99742139, 0.99750619,
       0.99759046, 0.99767355, 0.99775349, 0.99783187, 0.99790975,
       0.99798537, 0.99805937, 0.99813114, 0.99820182, 0.99827107,
       0.99833643, 0.99839992, 0.99846304, 0.99852492, 0.99858624,
       0.99864625, 0.99870417, 0.99876102, 0.99881553, 0.99886908,
       0.99892157, 0.99897347, 0.99902403, 0.99907222, 0.99911985,
       0.99916603, 0.99921085, 0.99925486, 0.99929824, 0.99933903,
       0.99937915, 0.99941845, 0.99945591, 0.99949101, 0.99952521,
       0.99955892, 0.99959168, 0.9996227 , 0.99965256, 0.99968086,
       0.99970851, 0.99973444, 0.99975822, 0.99978145, 0.99980309,
       0.99982412, 0.99984342, 0.99986216, 0.99987977, 0.99989647,
       0.99991173, 0.99992625, 0.99993921, 0.99995122, 0.99996211,
       0.99997252, 0.99998197, 0.99999037, 0.99999737, 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        ])

In [13]:
np.where(np.cumsum(pca.explained_variance_ratio_) == 1.)

(array([], dtype=int64),)

In [14]:
pca = PCA(n_components=30, whiten=True)
pca = pca.fit(X_train)
X_train = pca.transform(X_train)
X_test = pca.transform(X_test)

In [15]:
model = LinearRegression()
model.fit(X_train, y_train)
print(f"R2 на train: {model.score(X_train, y_train)}")
print(f"R2 на test: {model.score(X_test, y_test)}")

R2 на train: 0.8138622129346095
R2 на test: 0.8301002328138793

# PCA по шагам

Реализовать PCA по шагам (слайд 12 презентации) самостоятельно. Применить к данным, которые мы смотрели выше. Посмотрить модель линейной регрессии, сравнить качество модели.

In [16]:
df = pd.read_csv("D:/ProjectPython/Анализ даных/Пакеты прикладных программ/FOOD-DATA-GROUP1 (1).csv").loc[ :,'Caloric Value':'Zinc']
Y, X = df['Caloric Value'], df.loc[:, 'Fat':'Zinc']
df

,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,Cholesterol,...,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc
0,51,5.0,2.900,1.300,0.200,0.8,0.500,0.9,0.0,14.6,...,0.100,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039
1,215,19.4,10.900,4.900,0.800,3.1,2.700,7.8,0.0,62.9,...,0.045,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700
2,49,3.6,2.300,0.900,0.000,0.9,3.400,0.8,0.1,0.0,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000
3,30,2.0,1.300,0.500,0.002,1.5,0.091,1.5,0.0,9.8,...,0.011,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035
4,30,2.3,1.400,0.600,0.042,1.2,0.900,1.2,0.0,8.1,...,0.019,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
546,159,5.9,1.300,2.800,1.400,0.0,0.000,24.9,0.0,31.3,...,0.039,15.000,0.300,1.200,24.500,0.055,223.000,238.0,0.027,0.400
547,50,3.4,0.500,1.600,0.600,0.0,0.000,4.6,0.0,9.1,...,0.094,7.400,0.015,0.100,4.800,0.047,42.500,82.9,0.050,0.076
548,33,0.3,0.049,0.006,0.055,0.0,0.000,7.1,0.0,21.8,...,0.078,13.900,0.001,0.400,15.300,0.075,71.000,117.4,0.063,0.100
549,147,1.3,0.300,0.400,0.400,0.0,0.000,31.8,0.0,44.9,...,0.097,24.500,0.400,0.700,31.300,0.091,179.500,575.3,0.030,0.700
550,373,12.3,2.800,4.300,3.700,0.0,0.000,65.5,0.0,167.4,...,0.000,62.600,0.200,1.100,62.600,0.048,702.000,1036.8,0.026,1.200

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=14)
X_train

,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,Cholesterol,Sodium,...,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc
72,6.1,1.3,2.0,2.1,25.1,4.5,8.4,1.8,11.9,0.300,...,0.064,28.9,0.024,1.3,17.0,0.300,77.4,180.2,0.071,0.8
88,10.4,2.2,4.3,3.1,5.1,0.0,11.3,0.2,82.2,0.500,...,0.000,202.2,0.400,1.1,25.2,0.300,226.8,162.0,0.029,2.1
55,4.7,1.7,2.2,0.5,1.3,0.0,4.2,0.0,10.6,0.300,...,0.000,13.2,0.078,0.3,4.2,0.094,35.0,74.8,0.025,0.6
215,7.8,1.7,2.0,3.5,23.1,0.0,9.8,0.0,7.7,2.100,...,0.000,43.9,0.300,1.8,7.7,0.500,108.4,477.3,0.000,2.3
282,9.1,2.5,3.8,2.1,0.0,0.0,20.4,0.0,107.4,0.500,...,0.000,19.1,0.037,0.9,20.0,0.095,202.9,246.6,0.040,1.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,1.5,0.3,0.2,0.5,0.0,0.0,41.1,0.0,99.3,0.100,...,0.021,37.0,0.023,0.9,73.9,0.013,468.9,954.0,0.096,1.0
327,18.0,9.0,3.7,3.5,45.4,0.0,32.2,0.0,77.4,1.600,...,0.000,183.0,0.200,5.1,40.5,0.300,401.3,345.0,0.021,5.4
406,4.5,1.1,0.9,1.7,0.0,0.0,31.3,0.0,86.3,0.082,...,0.001,66.4,0.008,0.9,38.2,0.086,307.1,476.4,0.090,0.8
268,10.1,2.1,3.3,3.8,5.1,0.0,9.2,0.0,47.1,0.300,...,0.000,15.4,0.200,0.3,9.7,0.015,84.5,98.1,0.003,0.5
344,3.7,0.7,1.1,1.3,0.0,0.0,26.6,0.0,65.2,0.000,...,0.000,111.3,0.300,2.1,47.7,1.000,333.9,604.2,0.056,1.2

In [29]:
X_train = X_train.apply(lambda x: (x-x.mean())/x.std(), axis=0)
X_train

,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,Cholesterol,Sodium,...,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc
72,-0.359401,-0.430353,-0.355820,0.006114,0.459237,0.293227,-0.510848,0.372526,-0.693956,-0.443349,...,-0.135413,-0.383818,-0.189568,-0.104505,-0.370171,-0.251336,-0.569322,-0.425103,-0.238527,-0.277487
88,-0.005514,-0.269509,0.096874,0.329900,-0.539817,-0.383883,-0.354690,-0.425422,0.334817,-0.103955,...,-0.284642,0.634947,-0.180871,-0.214710,-0.173805,-0.251336,0.056858,-0.474349,-0.238812,0.363809
55,-0.474621,-0.358867,-0.316455,-0.511942,-0.729637,-0.383883,-0.737009,-0.525165,-0.712980,-0.443349,...,-0.284642,-0.476112,-0.188319,-0.655531,-0.676693,-0.267835,-0.747034,-0.710299,-0.238839,-0.376148
215,-0.219492,-0.358867,-0.355820,0.459414,0.359331,-0.383883,-0.435461,-0.525165,-0.755419,2.611197,...,-0.284642,-0.295639,-0.183184,0.171008,-0.592878,-0.235318,-0.439392,0.378805,-0.239009,0.462470
282,-0.112503,-0.215895,-0.001537,0.006114,-0.794576,-0.383883,0.135324,-0.525165,0.703594,-0.103955,...,-0.284642,-0.441428,-0.189268,-0.324915,-0.298330,-0.267754,-0.043314,-0.245435,-0.238737,0.166487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,-0.737979,-0.609067,-0.710103,-0.511942,-0.794576,-0.383883,1.249972,-0.525165,0.585059,-0.782743,...,-0.235676,-0.336201,-0.189591,-0.324915,0.992417,-0.274322,1.071572,1.668683,-0.238357,-0.178826
327,0.619962,0.945750,-0.021220,0.459414,1.473276,-0.383883,0.770727,-0.525165,0.264573,1.762712,...,-0.284642,0.522077,-0.185497,1.989394,0.192585,-0.251336,0.788240,0.020821,-0.238866,1.991715
406,-0.491080,-0.466095,-0.572326,-0.123400,-0.794576,-0.383883,0.722264,-0.525165,0.394816,-0.813288,...,-0.282310,-0.163370,-0.189938,-0.324915,0.137507,-0.268475,0.393419,0.376369,-0.238398,-0.277487
268,-0.030204,-0.287381,-0.099949,0.556550,-0.539817,-0.383883,-0.467770,-0.525165,-0.178838,-0.443349,...,-0.284642,-0.463179,-0.185497,-0.655531,-0.544984,-0.274162,-0.539564,-0.647253,-0.238988,-0.425479
344,-0.556920,-0.537581,-0.532962,-0.252914,-0.794576,-0.383883,0.469180,-0.525165,0.086038,-0.952440,...,-0.284642,0.100580,-0.183184,0.336316,0.365004,-0.195274,0.505746,0.722177,-0.238628,-0.080165

In [28]:
COV = X_train.cov()
COV

,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,Cholesterol,Sodium,...,Vitamin K,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc
Fat,1.000000,0.804840,0.817526,0.694171,0.472737,0.260803,0.396321,0.224145,0.465297,0.356599,...,0.083895,0.435327,0.153273,0.449595,0.327124,0.105497,0.441075,0.329103,0.103846,0.290919
Saturated Fats,0.804840,1.000000,0.736666,0.319074,0.329485,0.136214,0.172261,0.105398,0.308735,0.302222,...,0.030090,0.526246,0.119483,0.278770,0.148487,0.043836,0.294753,0.167687,0.044713,0.265746
Monounsaturated Fats,0.817526,0.736666,1.000000,0.533965,0.319546,0.135785,0.268072,0.154271,0.354630,0.220172,...,0.075934,0.258006,0.133214,0.339693,0.248927,0.087692,0.300580,0.215814,0.091242,0.197171
Polyunsaturated Fats,0.694171,0.319074,0.533965,1.000000,0.486295,0.345587,0.379962,0.321446,0.305722,0.288482,...,0.094590,0.119471,0.105308,0.413902,0.286140,0.114558,0.321925,0.277308,0.102462,0.142496
Carbohydrates,0.472737,0.329485,0.319546,0.486295,1.000000,0.614420,-0.079062,0.572469,-0.085552,0.454053,...,0.116334,0.086212,0.237742,0.419578,0.005957,0.176447,-0.039329,0.072216,0.163399,0.097635
Sugars,0.260803,0.136214,0.135785,0.345587,0.614420,1.000000,-0.020775,0.308592,-0.053294,0.162208,...,0.065815,0.066449,0.109805,0.199062,-0.027540,0.064266,-0.011525,-0.005666,0.070705,0.019821
Protein,0.396321,0.172261,0.268072,0.379962,-0.079062,-0.020775,1.000000,-0.067759,0.727217,0.054413,...,0.076634,0.274011,0.059680,0.306925,0.716305,0.119729,0.801324,0.768899,0.122208,0.288944
Dietary Fiber,0.224145,0.105398,0.154271,0.321446,0.572469,0.308592,-0.067759,1.000000,-0.183637,0.321666,...,0.161397,0.000798,0.190963,0.293003,0.011986,0.240442,-0.097275,0.028666,0.224986,0.057344
Cholesterol,0.465297,0.308735,0.354630,0.305722,-0.085552,-0.053294,0.727217,-0.183637,1.000000,0.046316,...,0.033410,0.292697,0.024446,0.283490,0.516007,0.049418,0.663868,0.536596,0.042745,0.255476
Sodium,0.356599,0.302222,0.220172,0.288482,0.454053,0.162208,0.054413,0.321666,0.046316,1.000000,...,0.073275,0.275836,0.154159,0.320487,0.019335,0.103907,0.104185,0.085671,0.094117,0.284027
Water,0.207545,0.022650,0.118553,0.294599,0.193310,0.157395,0.480232,0.270815,0.260057,0.457951,...,0.033314,0.046322,0.037851,0.295441,0.432606,0.078815,0.357990,0.553439,0.077243,0.235096
Vitamin A,0.330231,0.328208,0.291836,0.100715,0.048776,0.015720,0.211714,0.004194,0.295638,0.034544,...,0.208334,0.109872,0.387638,-0.050265,0.130071,0.277896,0.138764,0.167427,0.255169,-0.009860
Vitamin B1,0.372165,0.235211,0.262619,0.307510,0.350502,0.128654,0.290674,0.150960,0.241309,0.125943,...,-0.119115,0.101291,-0.110968,0.568943,0.263135,-0.124114,0.317635,0.296641,-0.126861,0.224937
Vitamin B11,0.243282,0.147065,0.186650,0.213545,0.277257,0.121634,0.163368,0.205290,0.088113,0.167197,...,0.485591,-0.088380,0.838979,-0.033936,-0.051065,0.689505,-0.093592,0.068477,0.648835,-0.061086
Vitamin B12,0.080612,0.068018,0.031567,-0.018387,-0.060789,-0.064676,0.178271,-0.091614,0.200357,-0.051335,...,0.158073,0.047187,0.422477,-0.085835,0.098363,0.209408,0.080859,0.052485,0.208093,-0.029373
Vitamin B2,0.399691,0.387945,0.258468,0.184764,0.290295,0.106103,0.281161,0.059557,0.335057,0.172334,...,-0.119079,0.366721,-0.097130,0.398621,0.338640,-0.131615,0.420593,0.406264,-0.130940,0.233997
Vitamin B3,0.341075,0.089903,0.238793,0.423376,-0.001868,0.024272,0.750104,-0.043471,0.504438,0.037516,...,-0.129177,0.122557,-0.101381,0.332068,0.633743,-0.142637,0.687463,0.623738,-0.133758,0.198035
Vitamin B5,0.260132,0.140329,0.198294,0.238228,0.132943,0.052329,0.400231,0.043429,0.271848,0.081201,...,0.655651,-0.033951,0.485873,-0.045936,0.077781,0.749584,0.056292,0.286315,0.771473,-0.074088
Vitamin B6,0.213239,0.024322,0.161585,0.278713,-0.037967,-0.027992,0.633732,0.043474,0.414680,-0.011195,...,0.343940,-0.028362,0.201735,0.108568,0.404819,0.485536,0.395160,0.562144,0.462125,0.022024
Vitamin C,0.102518,0.027101,0.042331,0.173611,0.220672,0.131504,0.142857,0.159759,0.036998,0.152277,...,-0.067743,0.034631,-0.065931,0.298723,0.258398,-0.064059,0.116340,0.285840,-0.075126,0.174375
Vitamin D,0.138980,0.099862,0.122606,0.110322,0.217323,0.097047,0.045612,0.172145,0.009733,0.155372,...,0.360087,-0.059579,0.822693,-0.074035,-0.076861,0.471904,-0.098737,-0.010576,0.563261,-0.074960
Vitamin E,0.299999,0.093637,0.223420,0.442934,0.069175,0.128674,0.318243,0.151759,0.268862,0.134123,...,-0.070315,0.143186,-0.078867,0.146354,0.260772,-0.107882,0.395326,0.295994,-0.100915,0.035277
Vitamin K,0.083895,0.030090,0.075934,0.094590,0.116334,0.065815,0.076634,0.161397,0.033410,0.073275,...,1.000000,-0.113188,0.437308,-0.144502,-0.165099,0.729900,-0.196624,-0.021331,0.772381,-0.149276
Calcium,0.435327,0.526246,0.258006,0.119471,0.086212,0.066449,0.274011,0.000798,0.292697,0.275836,...,-0.113188,1.000000,-0.103227,0.149685,0.226692,-0.141060,0.543220,0.185998,-0.132389,0.324648
Copper,0.153273,0.119483,0.133214,0.105308,0.237742,0.109805,0.059680,0.190963,0.024446,0.154159,...,0.437308,-0.103227,1.000000,-0.118462,-0.126713,0.643892,-0.165864,-0.023222,0.606413,-0.118017
Iron,0.449595,0.278770,0.339693,0.413902,0.419578,0.199062,0.306925,0.293003,0.283490,0.320487,...,-0.144502,0.149685,-0.118462,1.000000,0.309238,-0.139515,0.300083,0.289025,-0.158420,0.494089
Magnesium,0.327124,0.148487,0.248927,0.286140,0.005957,-0.027540,0.716305,0.011986,0.516007,0.019335,...,-0.165099,0.226692,-0.126713,0.309238,1.000000,-0.176123,0.742483,0.759459,-0.169464,0.275906
Manganese,0.105497,0.043836,0.087692,0.114558,0.176447,0.064266,0.119729,0.240442,0.049418,0.103907,...,0.729900,-0.141060,0.643892,-0.139515,-0.176123,1.000000,-0.223493,-0.001814,0.952203,-0.155241
Phosphorus,0.441075,0.294753,0.300580,0.321925,-0.039329,-0.011525,0.801324,-0.097275,0.663868,0.104185,...,-0.196624,0.543220,-0.165864,0.300083,0.742483,-0.223493,1.000000,0.725230,-0.213315,0.347967
Potassium,0.329103,0.167687,0.215814,0.277308,0.072216,-0.005666,0.768899,0.028666,0.536596,0.085671,...,-0.021331,0.185998,-0.023222,0.289025,0.759459,-0.001814,0.725230,1.000000,0.002486,0.205144
Selenium,0.103846,0.044713,0.091242,0.102462,0.163399,0.070705,0.122208,0.224986,0.042745,0.094117,...,0.772381,-0.132389,0.606413,-0.158420,-0.169464,0.952203,-0.213315,0.002486,1.000000,-0.154656
Zinc,0.290919,0.265746,0.197171,0.142496,0.097635,0.019821,0.288944,0.057344,0.255476,0.284027,...,-0.149276,0.324648,-0.118017,0.494089,0.275906,-0.155241,0.347967,0.205144,-0.154656,1.000000

In [21]:
sorted(np.linalg.eigvals(COV), reverse=True)
idx = np.argsort(np.linalg.eigvals(COV))[::-1]

In [22]:
eigenvalues, eigenvectors = np.linalg.eig(COV)
eigenvectors[idx]

array([[-0.28195022,  0.0125342 ,  0.21133629, ...,  0.03738605,
         0.07577596,  0.00290371],
       [-0.19414152,  0.00472134,  0.22611377, ..., -0.09330835,
        -0.09493537, -0.18582699],
       [-0.22014346,  0.01963577,  0.18151717, ..., -0.03770659,
        -0.01950702, -0.01860695],
       ...,
       [-0.10133158, -0.06169215,  0.06506213, ...,  0.08557312,
         0.00779394, -0.12870198],
       [-0.20890668,  0.10908195, -0.26601019, ...,  0.21269074,
        -0.13923938,  0.24428836],
       [-0.18352796, -0.10844688,  0.08656535, ...,  0.01460195,
         0.17787878,  0.01393191]], shape=(32, 32))

In [23]:
model = LinearRegression()
model.fit(X_train, y_train)
print(f"R2 на train: {model.score(X_train, y_train)}")
print(f"R2 на test: {model.score(X_test, y_test)}")
X_train, y_train

R2 на train: 0.9979336473678695
R2 на test: -426.01715774955085

(          Fat  Saturated Fats  Monounsaturated Fats  Polyunsaturated Fats  \
 72  -0.359401       -0.430353             -0.355820              0.006114
 88  -0.005514       -0.269509              0.096874              0.329900
 55  -0.474621       -0.358867             -0.316455             -0.511942
 215 -0.219492       -0.358867             -0.355820              0.459414
 282 -0.112503       -0.215895             -0.001537              0.006114
 ..        ...             ...                   ...                   ...
 358 -0.737979       -0.609067             -0.710103             -0.511942
 327  0.619962        0.945750             -0.021220              0.459414
 406 -0.491080       -0.466095             -0.572326             -0.123400
 268 -0.030204       -0.287381             -0.099949              0.556550
 344 -0.556920       -0.537581             -0.532962             -0.252914

      Carbohydrates    Sugars   Protein  Dietary Fiber  Cholesterol    Sodium  \
 72        0.459237  0.293227 -0.510848       0.372526    -0.693956 -0.443349
 88       -0.539817 -0.383883 -0.354690      -0.425422     0.334817 -0.103955
 55       -0.729637 -0.383883 -0.737009      -0.525165    -0.712980 -0.443349
 215       0.359331 -0.383883 -0.435461      -0.525165    -0.755419  2.611197
 282      -0.794576 -0.383883  0.135324      -0.525165     0.703594 -0.103955
 ..             ...       ...       ...            ...          ...       ...
 358      -0.794576 -0.383883  1.249972      -0.525165     0.585059 -0.782743
 327       1.473276 -0.383883  0.770727      -0.525165     0.264573  1.762712
 406      -0.794576 -0.383883  0.722264      -0.525165     0.394816 -0.813288
 268      -0.539817 -0.383883 -0.467770      -0.525165    -0.178838 -0.443349
 344      -0.794576 -0.383883  0.469180      -0.525165     0.086038 -0.952440

      ...  Vitamin K   Calcium    Copper      Iron  Magnesium  Manganese  \
 72   ...  -0.135413 -0.383818 -0.189568 -0.104505  -0.370171  -0.251336
 88   ...  -0.284642  0.634947 -0.180871 -0.214710  -0.173805  -0.251336
 55   ...  -0.284642 -0.476112 -0.188319 -0.655531  -0.676693  -0.267835
 215  ...  -0.284642 -0.295639 -0.183184  0.171008  -0.592878  -0.235318
 282  ...  -0.284642 -0.441428 -0.189268 -0.324915  -0.298330  -0.267754
 ..   ...        ...       ...       ...       ...        ...        ...
 358  ...  -0.235676 -0.336201 -0.189591 -0.324915   0.992417  -0.274322
 327  ...  -0.284642  0.522077 -0.185497  1.989394   0.192585  -0.251336
 406  ...  -0.282310 -0.163370 -0.189938 -0.324915   0.137507  -0.268475
 268  ...  -0.284642 -0.463179 -0.185497 -0.655531  -0.544984  -0.274162
 344  ...  -0.284642  0.100580 -0.183184  0.336316   0.365004  -0.195274

      Phosphorus  Potassium  Selenium      Zinc
 72    -0.569322  -0.425103 -0.238527 -0.277487
 88     0.056858  -0.474349 -0.238812  0.363809
 55    -0.747034  -0.710299 -0.238839 -0.376148
 215   -0.439392   0.378805 -0.239009  0.462470
 282   -0.043314  -0.245435 -0.238737  0.166487
 ..          ...        ...       ...       ...
 358    1.071572   1.668683 -0.238357 -0.178826
 327    0.788240   0.020821 -0.238866  1.991715
 406    0.393419   0.376369 -0.238398 -0.277487
 268   -0.539564  -0.647253 -0.238988 -0.425479
 344    0.505746   0.722177 -0.238628 -0.080165

 [440 rows x 32 columns],
 72     189
 88     160
 55      65
 215    201
 282    163
       ...
 358    189
 327    473
 406    174
 268    148
 344    146
 Name: Caloric Value, Length: 440, dtype: int64)

In [24]:
X_G_train = X_train@eigenvectors[idx][:11].T
X_G_test = X_test@eigenvectors[idx][:11].T
X_G_train

,0,1,2,3,4,5,6,7,8,9,10
72,3.632345,-1.781258,-1.364389,-1.204829,-0.374488,0.265607,0.094262,-0.042041,-0.213221,0.319994,-0.174231
88,-0.136720,-0.023366,-0.239918,0.002540,-0.216373,-0.615544,0.001636,0.048435,0.137339,0.045638,-0.304949
55,-0.560145,-0.433895,-0.739671,-0.017086,-0.340681,-0.191328,0.932296,0.439543,0.452642,0.597956,0.023903
215,0.878883,0.275329,0.262734,0.369555,-0.131360,0.927747,0.376153,-0.155016,0.590962,-1.244807,-0.111112
282,-0.491695,0.184115,-0.102748,-0.263131,-0.257832,-0.554850,0.066688,-0.007584,-0.129703,0.104138,-0.225508
...,...,...,...,...,...,...,...,...,...,...,...
358,-0.476348,-0.707712,0.354671,-0.038341,0.631585,-1.165972,-0.478722,-0.031587,0.559253,0.460354,-0.065867
327,0.343708,0.707795,-0.186311,1.006555,0.365195,0.617682,-0.763035,-2.710558,-0.282175,-0.925067,-0.113678
406,-0.716731,0.020973,0.175112,-0.424545,-0.131466,-0.766151,-0.275222,-0.029019,0.505579,0.216828,0.158979
268,-0.354729,0.121656,-0.340946,-0.319739,-0.459831,-0.547974,0.672940,0.235066,0.122999,0.378933,-0.651446
344,-0.482271,-0.182059,-0.296830,-0.130448,0.311958,-1.145664,0.117878,0.147887,0.557705,0.348822,0.023586

In [25]:
model = LinearRegression()
model.fit(X_G_train, y_train)
print(f"R2 на train: {model.score(X_G_train, y_train)}")
print(f"R2 на train: {model.score(X_G_test, y_test)}")

R2 на train: 0.8655658955773045
R2 на train: -2204.1887183241392

In [33]:
scaler = StandardScaler() # стандартизуем
X_train = scaler.fit_transform(X_train)  
X_test = scaler.transform(X_test)
pd.DataFrame(X_train)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,-0.359810,-0.430842,-0.356225,0.006121,0.459759,0.293561,-0.511430,0.372950,-0.694746,-0.443854,...,-0.135567,-0.384255,-0.189784,-0.104624,-0.370592,-0.251622,-0.569971,-0.425587,-0.238798,-0.277803
1,-0.005520,-0.269816,0.096985,0.330275,-0.540431,-0.384320,-0.355094,-0.425906,0.335198,-0.104073,...,-0.284966,0.635670,-0.181077,-0.214954,-0.174003,-0.251622,0.056923,-0.474889,-0.239084,0.364223
2,-0.475161,-0.359275,-0.316816,-0.512525,-0.730468,-0.384320,-0.737847,-0.525763,-0.713792,-0.443854,...,-0.284966,-0.476654,-0.188534,-0.656277,-0.677463,-0.268139,-0.747884,-0.711108,-0.239111,-0.376577
3,-0.219742,-0.359275,-0.356225,0.459937,0.359740,-0.384320,-0.435957,-0.525763,-0.756279,2.614169,...,-0.284966,-0.295975,-0.183393,0.171203,-0.593553,-0.235586,-0.439892,0.379236,-0.239281,0.462996
4,-0.112631,-0.216141,-0.001539,0.006121,-0.795480,-0.384320,0.135478,-0.525763,0.704395,-0.104073,...,-0.284966,-0.441931,-0.189483,-0.325285,-0.298669,-0.268059,-0.043364,-0.245714,-0.239009,0.166677
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,-0.738819,-0.609761,-0.710911,-0.512525,-0.795480,-0.384320,1.251395,-0.525763,0.585725,-0.783634,...,-0.235944,-0.336584,-0.189807,-0.325285,0.993547,-0.274634,1.072792,1.670582,-0.238628,-0.179030
436,0.620667,0.946827,-0.021244,0.459937,1.474953,-0.384320,0.771605,-0.525763,0.264875,1.764719,...,-0.284966,0.522672,-0.185708,1.991659,0.192805,-0.251622,0.789137,0.020845,-0.239138,1.993982
437,-0.491639,-0.466626,-0.572978,-0.123540,-0.795480,-0.384320,0.723086,-0.525763,0.395266,-0.814214,...,-0.282631,-0.163556,-0.190155,-0.325285,0.137664,-0.268781,0.393867,0.376798,-0.238669,-0.277803
438,-0.030238,-0.287708,-0.100063,0.557183,-0.540431,-0.384320,-0.468302,-0.525763,-0.179041,-0.443854,...,-0.284966,-0.463706,-0.185708,-0.656277,-0.545605,-0.274474,-0.540178,-0.647990,-0.239260,-0.425963
439,-0.557554,-0.538193,-0.533568,-0.253202,-0.795480,-0.384320,0.469714,-0.525763,0.086136,-0.953524,...,-0.284966,0.100695,-0.183393,0.336699,0.365420,-0.195496,0.506322,0.722999,-0.238900,-0.080257

In [34]:
def PCA(X, Y, n_components=2, random_state=14):
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=random_state) #разбиваем на train и test

    scaler = StandardScaler() # стандартизуем
    X_train = scaler.fit_transform(X_train)  
    X_test = scaler.transform(X_test)

    model = LinearRegression() #метрики на полных данных
    model.fit(X_train, y_train)
    print(f"R2 на train, полные данные: {model.score(X_train, y_train)}")
    print(f"R2 на test, полные данные: {model.score(X_test, y_test)}")

    COV = pd.DataFrame(X_train).cov() #матрица ковариации
    
    idx = np.argsort(np.linalg.eigvals(COV))[::-1] #собствеенные векторы и значения
    eigenvalues, eigenvectors = np.linalg.eig(COV)

    X_G_train = X_train@eigenvectors[idx][:n_components].T #данные в пространстве n главных компонент
    X_G_test = X_test@eigenvectors[idx][:n_components].T

    model = LinearRegression()
    model.fit(X_G_train, y_train)
    print(f"R2 на train, в пространстве {n_components} главных компонент: {model.score(X_G_train, y_train)}")
    print(f"R2 на train, в пространстве {n_components} главных компонент: {model.score(X_G_test, y_test)}")

In [40]:
PCA( df.loc[:, 'Fat':'Zinc'], df['Caloric Value'], n_components=12)

R2 на train, полные данные: 0.9979336473678695
R2 на test, полные данные: 0.9982260727500135
R2 на train, в пространстве 12 главных компонент: 0.8686387079139777
R2 на train, в пространстве 12 главных компонент: -12.49801133341465