In [27]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet

In [49]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import r2_score, mean_absolute_percentage_error, mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score, KFold, GridSearchCV

# <center> Подбор гиперпараметров </center>

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/katarina74/ml_lessons/main/lesson_2/data/techparams_train.csv")
X = df.drop(["target", "index"], axis=1)
y = df[["target"]]

ordinal = ['back-suspension', 'cylinders-order', 'engine-feeding', 'configurations_seats']
numerical = ['battery-capacity', 'charge-time', 'compression', 'consumption-mixed', 'cylinders-value', 'engine-start', 'engine-stop', 'luxury',
             'max-speed', 'power-electro-kw','valves','weight','configurations_auto-premiere','configurations_back-wheel-base','configurations_tank-volume',
             'supergen_year-stop']
catigorial = ['engine-start','supergen_year-stop','engine-stop','engine-type','gear-type', 'supply-system', 'valvetrain', 'configurations_front-brake', 'configurations_safety-rating','models_country-from',
              'models_group', 'models_light-and-commercial','models_male']

X_crop = X.drop(catigorial, axis=1)

train_X, test_X, train_y, test_y = train_test_split(X_crop, y, test_size=0.33, random_state=42)

In [4]:
train_X.info()

<class 'pandas.DataFrame'>
Index: 28974 entries, 22607 to 15795
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   back-suspension                 28974 non-null  int64
 1   battery-capacity                28974 non-null  float64
 2   charge-time                     28974 non-null  int64
 3   compression                     28974 non-null  float64
 4   consumption-mixed               28974 non-null  float64
 5   cylinders-order                 28974 non-null  int64
 6   cylinders-value                 28974 non-null  int64
 7   engine-feeding                  28974 non-null  int64
 8   luxury                          28974 non-null  int64
 9   max-speed                       28974 non-null  float64
 10  power-electro-kw                28974 non-null  float64
 11  valves                          28974 non-null  int64
 12  weight                          28974 non-null  float64
 13  configurations_auto-premiere    28974 non-null  int64
 14  configurations_back-wheel-base  28974 non-null  float64
 15  configurations_seats            28974 non-null  int64
 16  configurations_tank-volume      28974 non-null  float64
dtypes: float64(8), int64(9)
memory usage: 4.0 MB

In [5]:
train_X.head()

,back-suspension,battery-capacity,charge-time,compression,consumption-mixed,cylinders-order,cylinders-value,engine-feeding,luxury,max-speed,power-electro-kw,valves,weight,configurations_auto-premiere,configurations_back-wheel-base,configurations_seats,configurations_tank-volume
22607,3,-1.0,11636,9.5,-1.0,0,4,4,11923,160.0,-1.0,2,1290.0,11642,1415.0,13,50.0
36531,8,-1.0,31764,9.0,-1.0,0,4,0,31915,145.0,-1.0,0,935.0,31785,1310.0,13,48.0
24048,8,-1.0,2773,8.8,6.8,0,4,4,2258,221.0,-1.0,2,1373.0,2763,1558.0,13,56.0
34819,3,-1.0,52039,14.0,5.3,0,4,5,51108,198.0,-1.0,2,1430.0,52081,1590.0,13,56.0
1328,3,-1.0,20689,18.0,7.5,0,5,5,20228,195.0,-1.0,2,1485.0,20685,1560.0,13,70.0

In [7]:
reg = LinearRegression().fit(train_X, train_y)

In [8]:
pred_test = reg.predict(test_X)

In [9]:
mean_absolute_percentage_error(test_y, pred_test)

0.04764777849052335

**Задание:**
1. Разделить выборку на тестовую и обучающую. Обучать модель на данных с декабря 2022 года по конец августа 2023 года. Тестирование проводить на данных за сентябрь 2023 года. 
2. Преобразовать данные к одной шкале, используя метод StandartScaler. 
3. Создать фиктивные переменные для номинативных показателей. Можно включать не все номинативные показатели, но объяснить, какие были исключены и почему. 
4. Построить модель логистической регрессии с базовыми параметрами (BaseLine). Оценить качество полученной модели на тестовой и на обучающей выборке.
5. Используя метод обучения по сетке (https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) и кросс-валидацию результатов (https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html#sklearn.model_selection.StratifiedKFold), подобрать оптимальные значения гиперпараметров модели: 
    - penalty
    - C
    - l1_ratio
6. Получить результаты обучения лучшей модели. Сравнить результаты с BaseLine.

При подборе параметров учесть, что не все оптимизаторы способны осуществлять 'l1' и 'l2' регуляризацию.
При обучении отобразить прогресс выполнения.

**Задание *:** выявить, в чем различия между различными оптимизаторами (параметр 'solver') при обучении. Сравнить быстродейтсвие и эффективность оптимизаторов на нашем наборе данных.

In [21]:
X[catigorial]

,engine-start,supergen_year-stop,engine-stop,engine-type,gear-type,supply-system,valvetrain,configurations_front-brake,configurations_safety-rating,models_country-from,models_group,models_light-and-commercial,models_male
0,2006,2018.0,2018,2,1,0,0,1,2,16,3,0,1
1,1982,1993.0,1993,2,2,0,0,4,2,34,3,0,1
2,2014,2019.0,2018,0,1,0,0,4,2,35,3,0,1
3,2000,2003.0,2003,2,1,1,1,4,2,10,3,0,1
4,2000,2005.0,2005,0,1,3,1,4,1,10,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43240,2004,2016.0,2016,2,1,0,0,1,2,15,3,0,1
43241,2013,2015.0,2015,2,1,3,0,4,2,10,3,0,1
43242,1991,1999.0,1999,2,1,0,1,4,2,16,3,0,1
43243,2002,2004.0,2004,2,0,3,0,1,2,28,3,0,1
43244,1982,1987.0,1984,2,2,0,1,1,2,16,3,0,0

In [15]:
model = LinearRegression()

In [11]:
scores = cross_val_score(model, train_X, train_y, cv = 10, scoring = 'neg_mean_absolute_percentage_error', verbose = 1)

[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.2s finished

In [12]:
print(scores)
(scores.mean(), scores.var())

[-0.04719492 -0.04804466 -0.0469994  -0.04572128 -0.04629913 -0.04656426
 -0.04794563 -0.04742356 -0.04580326 -0.04643183]

(np.float64(-0.04684279264412498), np.float64(6.02703280666682e-07))

In [22]:
kf = KFold(n_splits = 10, shuffle = True, random_state = 42)

In [23]:
fold_n = 1
for train_index, test_index in kf.split(train_X, train_y):
    model = LinearRegression()
    model.fit(train_X.iloc[train_index], train_y.iloc[train_index])
    print(fold_n, mean_absolute_percentage_error(train_y.iloc[test_index], model.predict(train_X.iloc[test_index])[:,0]))

1 0.047469641592408574
1 0.04814123828438822
1 0.04758550053743849
1 0.04619072877658265
1 0.047383952784324126
1 0.0466337171832134
1 0.04602221993114353
1 0.04642143799809971
1 0.04701052255346228
1 0.045518432242933185

### Подбор параметров модели

**Задание 1**

Реализовать подбор по сетке: 
1. Выбрать модель, которую будем улучшать (Ridge, Lasso или ElasticNet).
2. Разбить исходные данные на подгруппы для обучения.
3. Выбрать 1 гиперпараметр, значения которого необходимо подобрать. Определить диапазон значений, которые будем перебирать.
4. Для каждого значения из выбранного диапазона:
    - Обучить модель на каждой подгруппе.
    - Получить значение метрики на тесте.
    - Получить время обучения.
    - Усреднить метрику и время обучения по группам.
5. Выбрать то значение из дипазона, для которого усредненная метрика качества модели будет наилучшей.

In [39]:
import warnings
import time
from sklearn.exceptions import ConvergenceWarning

# Игнорируем только ConvergenceWarning
warnings.filterwarnings('ignore', category=ConvergenceWarning)

**Задание 2**

Используя функцию GridSearchCV подобрать гиперпараметры для Ridge, Lasso или ElasticNet. Сравнить качество улучшенной модели с LinearRegression.

In [48]:
fold_n = 3

kf = KFold(n_splits = fold_n, shuffle = True, random_state = 14)

mse, mape, time_, r2 = 0, 0, 0, 0
for l1_ratio_ in [0.3, 0.5, 0.7]:
    for alpha_ in [0.8, 0.9, 1.0, 1.1, 1.2]:
        for train_index, test_index in kf.split(train_X, train_y):
            start = time.perf_counter()
            model = ElasticNet(random_state=14, alpha=alpha_, l1_ratio=l1_ratio_)
            model.fit(train_X.iloc[train_index], train_y.iloc[train_index])
            end = time.perf_counter()

            mse_ = mean_squared_error(train_y.iloc[test_index], model.predict(train_X.iloc[test_index]))
            mape_ = mean_absolute_percentage_error(train_y.iloc[test_index], model.predict(train_X.iloc[test_index]))
            r2_ = r2_score(train_y.iloc[test_index], model.predict(train_X.iloc[test_index]))
            mse += mse_
            mape += mape_
            r2 += r2_
            time_ += end - start

        print(f'Для alpha = {alpha_} и l1_ratio = {l1_ratio_}, MSE_mean = {mse/fold_n}, MAPE_mean = {mape/fold_n}, time_mean = {time_/fold_n:.4f}, r2_mean = {r2/fold_n}')

        mse, mape, r2, time_ = 0, 0, 0, 0

Для alpha = 0.8 и l1_ratio = 0.3, MSE_mean = 33929.95080553303, MAPE_mean = 0.047327912420402955, time_mean = 1.1536, r2_mean = 0.38114379654914704
Для alpha = 0.9 и l1_ratio = 0.3, MSE_mean = 34024.097074811194, MAPE_mean = 0.04738813221506944, time_mean = 1.1225, r2_mean = 0.3794240682760983
Для alpha = 1.0 и l1_ratio = 0.3, MSE_mean = 34115.89882087868, MAPE_mean = 0.04744774463834631, time_mean = 1.1765, r2_mean = 0.37774712689177514
Для alpha = 1.1 и l1_ratio = 0.3, MSE_mean = 34205.4395813043, MAPE_mean = 0.04750639905281029, time_mean = 1.1233, r2_mean = 0.37611146679086155
Для alpha = 1.2 и l1_ratio = 0.3, MSE_mean = 34292.80628922983, MAPE_mean = 0.04756389750022214, time_mean = 1.1038, r2_mean = 0.37451551324200244
Для alpha = 0.8 и l1_ratio = 0.5, MSE_mean = 33711.368778034375, MAPE_mean = 0.04718251888884887, time_mean = 1.1052, r2_mean = 0.3851360646095565
Для alpha = 0.9 и l1_ratio = 0.5, MSE_mean = 33783.91320743145, MAPE_mean = 0.047230216239304484, time_mean = 1.0979, r2_mean = 0.3838111101708274
Для alpha = 1.0 и l1_ratio = 0.5, MSE_mean = 33855.31980186223, MAPE_mean = 0.04727707828967468, time_mean = 1.1183, r2_mean = 0.3825068636162367
Для alpha = 1.1 и l1_ratio = 0.5, MSE_mean = 33925.53978600486, MAPE_mean = 0.04732279593033036, time_mean = 1.0968, r2_mean = 0.3812242385720382
Для alpha = 1.2 и l1_ratio = 0.5, MSE_mean = 33994.564549340284, MAPE_mean = 0.04736687422121266, time_mean = 1.1392, r2_mean = 0.379963409076204
Для alpha = 0.8 и l1_ratio = 0.7, MSE_mean = 33480.24274625586, MAPE_mean = 0.04702451737374621, time_mean = 1.0478, r2_mean = 0.38935603716632566
Для alpha = 0.9 и l1_ratio = 0.7, MSE_mean = 33526.168075875765, MAPE_mean = 0.04705490965858949, time_mean = 1.0778, r2_mean = 0.3885175841928023
Для alpha = 1.0 и l1_ratio = 0.7, MSE_mean = 33572.263142715754, MAPE_mean = 0.04708556183561751, time_mean = 1.1876, r2_mean = 0.38767594880130724
Для alpha = 1.1 и l1_ratio = 0.7, MSE_mean = 33618.350266129535, MAPE_mean = 0.04711634182324024, time_mean = 1.1105, r2_mean = 0.38683438619475186
Для alpha = 1.2 и l1_ratio = 0.7, MSE_mean = 33664.29562045872, MAPE_mean = 0.04714656577126051, time_mean = 1.0693, r2_mean = 0.38599535366894605

In [54]:
model = ElasticNet(random_state=14)
param_grid = {'l1_ratio':[0.3, 0.4, 0.5, 0.7, 0.8], 'alpha':[0.8, 0.9, 1.0, 1.1, 1.2], 'fit_intercept':[True, False]}

grid_search = GridSearchCV(
    estimator=model,          
    param_grid=param_grid,     
    cv=5,                    
    scoring='neg_mean_squared_error',  
    verbose=1,                 
    n_jobs=-1                  
)

grid_search.fit(train_X, train_y)

Fitting 5 folds for each of 50 candidates, totalling 250 fits

GridSearchCV(cv=5, estimator=ElasticNet(random_state=14), n_jobs=-1,
             param_grid={'alpha': [0.8, 0.9, 1.0, 1.1, 1.2],
                         'fit_intercept': [True, False],
                         'l1_ratio': [0.3, 0.4, 0.5, 0.7, 0.8]},
             scoring='neg_mean_squared_error', verbose=1)