In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet

In [2]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, RobustScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.metrics import r2_score, mean_absolute_percentage_error
from sklearn.model_selection import cross_val_score, KFold, GridSearchCV

In [3]:
import plotly.express as px
import plotly.graph_objs as go
import sklearn

# <center> Подбор гиперпараметров </center>

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/katarina74/ml_lessons/main/lesson_2/data/techparams_train.csv")
X = df.drop(["target", "index"], axis=1)
y = df[["target"]]

ordinal = ['back-suspension', 'cylinders-order', 'engine-feeding', 'configurations_seats']
numerical = ['battery-capacity', 'charge-time', 'compression', 'consumption-mixed', 'cylinders-value', 'luxury',
             'max-speed', 'power-electro-kw','valves','weight','configurations_auto-premiere','configurations_back-wheel-base','configurations_tank-volume']
catigorial = ['engine-start','supergen_year-stop','engine-stop','engine-type','gear-type', 'supply-system', 'valvetrain', 'configurations_front-brake', 'configurations_safety-rating','models_country-from',
              'models_group', 'models_light-and-commercial','models_male']

#X_crop = X.drop(catigorial, axis=1)

train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
train_X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28974 entries, 22607 to 15795
Data columns (total 30 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   back-suspension                 28974 non-null  int64
 1   battery-capacity                28974 non-null  float64
 2   charge-time                     28974 non-null  int64
 3   compression                     28974 non-null  float64
 4   consumption-mixed               28974 non-null  float64
 5   cylinders-order                 28974 non-null  int64
 6   cylinders-value                 28974 non-null  int64
 7   engine-feeding                  28974 non-null  int64
 8   engine-start                    28974 non-null  int64
 9   engine-stop                     28974 non-null  int64
 10  engine-type                     28974 non-null  int64
 11  gear-type                       28974 non-null  int64
 12  luxury                          28974 non-null  int64
 13  max-speed                       28974 non-null  float64
 14  power-electro-kw                28974 non-null  float64
 15  supply-system                   28974 non-null  int64
 16  valves                          28974 non-null  int64
 17  valvetrain                      28974 non-null  int64
 18  weight                          28974 non-null  float64
 19  configurations_auto-premiere    28974 non-null  int64
 20  configurations_back-wheel-base  28974 non-null  float64
 21  configurations_front-brake      28974 non-null  int64
 22  configurations_safety-rating    28974 non-null  int64
 23  configurations_seats            28974 non-null  int64
 24  configurations_tank-volume      28974 non-null  float64
 25  supergen_year-stop              28974 non-null  float64
 26  models_country-from             28974 non-null  int64
 27  models_group                    28974 non-null  int64
 28  models_light-and-commercial     28974 non-null  int64
 29  models_male                     28974 non-null  int64
dtypes: float64(9), int64(21)
memory usage: 6.9 MB

In [ ]:
train_X.head()

,back-suspension,battery-capacity,charge-time,compression,consumption-mixed,cylinders-order,cylinders-value,engine-feeding,engine-start,engine-stop,...,configurations_back-wheel-base,configurations_front-brake,configurations_safety-rating,configurations_seats,configurations_tank-volume,supergen_year-stop,models_country-from,models_group,models_light-and-commercial,models_male
22607,3,-1.0,11636,9.5,-1.0,0,4,4,1997,2000,...,1415.0,4,2,13,50.0,2000.0,16,3,0,1
36531,8,-1.0,31764,9.0,-1.0,0,4,0,1990,1993,...,1310.0,1,2,13,48.0,1996.0,23,3,0,0
24048,8,-1.0,2773,8.8,6.8,0,4,4,2009,2012,...,1558.0,4,1,13,56.0,2012.0,10,3,0,1
34819,3,-1.0,52039,14.0,5.3,0,4,5,2015,2017,...,1590.0,4,2,13,56.0,2017.0,16,3,0,0
1328,3,-1.0,20689,18.0,7.5,0,5,5,2004,2005,...,1560.0,4,2,13,70.0,2009.0,28,3,0,1

In [ ]:
reg = LinearRegression().fit(train_X, train_y)

In [ ]:
pred_test = reg.predict(test_X)

In [ ]:
mean_absolute_percentage_error(test_y, pred_test)

0.044973108044071584

### Кросс валидация

In [ ]:
model = LinearRegression()

In [11]:
scores = cross_val_score(model, train_X, train_y, cv = 10, scoring = 'neg_mean_absolute_percentage_error', verbose = 1)

[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.4s finished

In [12]:
print(scores)
(scores.mean(), scores.var())

[-0.0451511  -0.0447811  -0.04466816 -0.04293119 -0.0432839  -0.04401972
 -0.04536235 -0.0451736  -0.0437018  -0.04388562]

(np.float64(-0.0442958545871149), np.float64(6.497167653032127e-07))

In [ ]:
kf = KFold(n_splits = 10, shuffle = True, random_state = 42)

In [14]:
fold_n = 1
for train_index, test_index in kf.split(train_X, train_y):
    model = LinearRegression()
    model.fit(train_X.iloc[train_index], train_y.iloc[train_index])
    print(fold_n, mean_absolute_percentage_error(train_y.iloc[test_index], model.predict(train_X.iloc[test_index])[:,0]))

1 0.04435009564656798
1 0.045874997817309915
1 0.044660013035448996
1 0.04402936701266291
1 0.04460401546854753

1 0.04400784942994144
1 0.04376047393111144
1 0.04405575460900875
1 0.04415463029449327
1 0.043354504564340555

### Pipeline

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
numerical_transformer = StandardScaler()

In [ ]:
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical),
        ('cat', categorical_transformer, catigorial)])

In [ ]:
train_X

,back-suspension,battery-capacity,charge-time,compression,consumption-mixed,cylinders-order,cylinders-value,engine-feeding,engine-start,engine-stop,...,configurations_back-wheel-base,configurations_front-brake,configurations_safety-rating,configurations_seats,configurations_tank-volume,supergen_year-stop,models_country-from,models_group,models_light-and-commercial,models_male
22607,3,-1.0,11636,9.5,-1.0,0,4,4,1997,2000,...,1415.0,4,2,13,50.0,2000.0,16,3,0,1
36531,8,-1.0,31764,9.0,-1.0,0,4,0,1990,1993,...,1310.0,1,2,13,48.0,1996.0,23,3,0,0
24048,8,-1.0,2773,8.8,6.8,0,4,4,2009,2012,...,1558.0,4,1,13,56.0,2012.0,10,3,0,1
34819,3,-1.0,52039,14.0,5.3,0,4,5,2015,2017,...,1590.0,4,2,13,56.0,2017.0,16,3,0,0
1328,3,-1.0,20689,18.0,7.5,0,5,5,2004,2005,...,1560.0,4,2,13,70.0,2009.0,28,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6265,6,-1.0,42729,16.5,4.7,0,4,5,2017,0,...,1630.0,4,2,13,68.0,-1.0,10,3,0,1
11284,0,-1.0,46093,8.1,-1.0,3,7,0,1987,1990,...,1486.0,4,2,13,82.0,1996.0,34,3,0,1
38158,3,-1.0,48819,10.0,7.6,0,4,2,2018,0,...,1636.0,4,2,13,62.0,-1.0,26,3,0,1
860,10,-1.0,9346,22.4,-1.0,0,4,6,1992,1995,...,1460.0,1,2,13,50.0,1995.0,16,3,0,1
15795,3,-1.0,43309,10.1,-1.0,3,7,4,2004,2007,...,1559.0,4,2,8,66.0,2007.0,35,3,0,1

In [ ]:
reg = LinearRegression()

In [ ]:
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', reg)])

In [22]:
model.fit(train_X, train_y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['battery-capacity',
                                                   'charge-time', 'compression',
                                                   'consumption-mixed',
                                                   'cylinders-value', 'luxury',
                                                   'max-speed',
                                                   'power-electro-kw', 'valves',
                                                   'weight',
                                                   'configurations_auto-premiere',
                                                   'configurations_back-wheel-base',
                                                   'configurations_tank-volume']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['engine-start',
                                                   'supergen_year-stop',
                                                   'engine-stop', 'engine-type',
                                                   'gear-type', 'supply-system',
                                                   'valvetrain',
                                                   'configurations_front-brake',
                                                   'configurations_safety-rating',
                                                   'models_country-from',
                                                   'models_group',
                                                   'models_light-and-commercial',
                                                   'models_male'])])),
                ('regressor', LinearRegression())])

In [ ]:
pred_test = model.predict(test_X)

In [ ]:
mean_absolute_percentage_error(test_y, pred_test)

0.04379747435611562

In [25]:
scores = cross_val_score(model, train_X, train_y, cv = 10, scoring = 'neg_mean_absolute_percentage_error', verbose = 1)

[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:   31.7s finished

In [26]:
print(scores)
(scores.mean(), scores.var())

[-0.04279724 -0.0427149  -0.04368984 -0.04260933 -0.04257747 -0.04289418
 -0.04496673 -0.04451464 -0.04305201 -0.0436945 ]

(np.float64(-0.04335108274774393), np.float64(6.355220966854175e-07))

### Подбор параметров модели

In [ ]:
reg = ElasticNet()
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', reg)])

In [ ]:
parameters = [
    {'regressor__alpha': [0.01, 0.5, 1]},
    {'regressor__l1_ratio': [0.01, 0.5, 1]}]

In [ ]:
kf = KFold(n_splits = 10, shuffle = True, random_state = 42)

In [30]:
model_cv = GridSearchCV(model, parameters, cv = kf, verbose = 2, scoring = 'neg_mean_absolute_percentage_error')

In [31]:
model_cv.fit(train_X, train_y)

Fitting 10 folds for each of 6 candidates, totalling 60 fits
[CV] END ..............................regressor__alpha=0.01; total time=  12.9s
[CV] END ..............................regressor__alpha=0.01; total time=  13.3s
[CV] END ..............................regressor__alpha=0.01; total time=  13.2s
[CV] END ..............................regressor__alpha=0.01; total time=  13.8s
[CV] END ..............................regressor__alpha=0.01; total time=  14.2s
[CV] END ..............................regressor__alpha=0.01; total time=  13.2s
[CV] END ..............................regressor__alpha=0.01; total time=  12.5s
[CV] END ..............................regressor__alpha=0.01; total time=  13.0s
[CV] END ..............................regressor__alpha=0.01; total time=  12.7s
[CV] END ..............................regressor__alpha=0.01; total time=  12.6s
[CV] END ...............................regressor__alpha=0.5; total time=   0.7s
[CV] END ...............................regressor__alpha=0.5; total time=   0.7s
[CV] END ...............................regressor__alpha=0.5; total time=   0.7s
[CV] END ...............................regressor__alpha=0.5; total time=   0.7s
[CV] END ...............................regressor__alpha=0.5; total time=   0.7s
[CV] END ...............................regressor__alpha=0.5; total time=   0.8s
[CV] END ...............................regressor__alpha=0.5; total time=   0.9s
[CV] END ...............................regressor__alpha=0.5; total time=   0.8s
[CV] END ...............................regressor__alpha=0.5; total time=   0.7s
[CV] END ...............................regressor__alpha=0.5; total time=   0.7s
[CV] END .................................regressor__alpha=1; total time=   0.5s
[CV] END .................................regressor__alpha=1; total time=   0.5s
[CV] END .................................regressor__alpha=1; total time=   0.5s
[CV] END .................................regressor__alpha=1; total time=   0.5s
[CV] END .................................regressor__alpha=1; total time=   0.5s
[CV] END .................................regressor__alpha=1; total time=   0.5s
[CV] END .................................regressor__alpha=1; total time=   0.5s
[CV] END .................................regressor__alpha=1; total time=   0.5s
[CV] END .................................regressor__alpha=1; total time=   0.5s
[CV] END .................................regressor__alpha=1; total time=   0.5s
[CV] END ...........................regressor__l1_ratio=0.01; total time=   0.5s
[CV] END ...........................regressor__l1_ratio=0.01; total time=   0.5s
[CV] END ...........................regressor__l1_ratio=0.01; total time=   0.5s
[CV] END ...........................regressor__l1_ratio=0.01; total time=   0.5s
[CV] END ...........................regressor__l1_ratio=0.01; total time=   0.5s
[CV] END ...........................regressor__l1_ratio=0.01; total time=   0.5s
[CV] END ...........................regressor__l1_ratio=0.01; total time=   0.5s
[CV] END ...........................regressor__l1_ratio=0.01; total time=   0.5s
[CV] END ...........................regressor__l1_ratio=0.01; total time=   0.7s
[CV] END ...........................regressor__l1_ratio=0.01; total time=   0.7s
[CV] END ............................regressor__l1_ratio=0.5; total time=   0.6s
[CV] END ............................regressor__l1_ratio=0.5; total time=   0.5s
[CV] END ............................regressor__l1_ratio=0.5; total time=   0.5s
[CV] END ............................regressor__l1_ratio=0.5; total time=   0.5s
[CV] END ............................regressor__l1_ratio=0.5; total time=   0.5s
[CV] END ............................regressor__l1_ratio=0.5; total time=   0.5s
[CV] END ............................regressor__l1_ratio=0.5; total time=   0.5s
[CV] END ............................regressor__l1_ratio=0.5; total time=   0.5s
[CV] END ............................regressor__l1_ratio=0.5; total time=   0.5s
[CV] END ............................regressor__l1_ratio=0.5; total time=   0.5s
[CV] END ..............................regressor__l1_ratio=1; total time=   3.0s
[CV] END ..............................regressor__l1_ratio=1; total time=   3.4s
[CV] END ..............................regressor__l1_ratio=1; total time=   3.5s
[CV] END ..............................regressor__l1_ratio=1; total time=   3.4s
[CV] END ..............................regressor__l1_ratio=1; total time=   3.3s
[CV] END ..............................regressor__l1_ratio=1; total time=   3.4s
[CV] END ..............................regressor__l1_ratio=1; total time=   3.1s
[CV] END ..............................regressor__l1_ratio=1; total time=   3.3s
[CV] END ..............................regressor__l1_ratio=1; total time=   3.4s
[CV] END ..............................regressor__l1_ratio=1; total time=   3.2s

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['battery-capacity',
                                                                          'charge-time',
                                                                          'compression',
                                                                          'consumption-mixed',
                                                                          'cylinders-value',
                                                                          'luxury',
                                                                          'max-speed',
                                                                          'power-electro-kw',
                                                                          'valves',
                                                                          'weight',
                                                                          'configurations_auto-premiere',
                                                                          'configuratio...
                                                                          'gear-type',
                                                                          'supply-system',
                                                                          'valvetrain',
                                                                          'configurations_front-brake',
                                                                          'configurations_safety-rating',
                                                                          'models_country-from',
                                                                          'models_group',
                                                                          'models_light-and-commercial',
                                                                          'models_male'])])),
                                       ('regressor', ElasticNet())]),
             param_grid=[{'regressor__alpha': [0.01, 0.5, 1]},
                         {'regressor__l1_ratio': [0.01, 0.5, 1]}],
             scoring='neg_mean_absolute_percentage_error', verbose=2)

In [32]:
results = model_cv.cv_results_
results.keys()

dict_keys(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time', 'param_regressor__alpha', 'param_regressor__l1_ratio', 'params', 'split0_test_score', 'split1_test_score', 'split2_test_score', 'split3_test_score', 'split4_test_score', 'split5_test_score', 'split6_test_score', 'split7_test_score', 'split8_test_score', 'split9_test_score', 'mean_test_score', 'std_test_score', 'rank_test_score'])

In [33]:
go.Figure(data = [
    go.Bar(y = results['mean_fit_time'], hovertext = [str(i) for i in results['params']]),
    go.Bar(y = -results['mean_test_score'])
                 ])

In [34]:
model_cv.best_params_

{'regressor__alpha': 0.01}

In [35]:
model_cv.best_score_

np.float64(-0.043459437509543675)

In [36]:
pred_test = model_cv.predict(test_X)

In [37]:
pred_test = model_cv.best_estimator_.predict(test_X)

In [38]:
mean_absolute_percentage_error(test_y, pred_test)

0.04399098501429684

### Optune

In [40]:
!pip install optuna
import optuna

Collecting optuna
  Downloading optuna-4.8.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.11)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.8.0-py3-none-any.whl (419 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 419.5/419.5 kB 4.4 MB/s eta 0:00:00a 0:00:01
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.8.0

In [41]:
reg = ElasticNet()
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', reg)])

In [42]:
parameters = [
    {'regressor__alpha': [0.01, 0.5, 1]},
    {'regressor__l1_ratio': [0.01, 0.5, 1]}]

In [43]:
param_distributions = {
        "regressor__alpha": optuna.distributions.FloatDistribution(0.01, 1),
        "regressor__l1_ratio": optuna.distributions.FloatDistribution(0.01,1),
    }

In [44]:
?optuna.integration.OptunaSearchCV

Object `optuna.integration.OptunaSearchCV` not found.

In [46]:
!pip install optuna-integration[sklearn]
optuna_search = optuna.integration.OptunaSearchCV(
        model, param_distributions, n_trials=10, timeout=600, verbose=2, scoring = 'neg_mean_absolute_percentage_error'
    )

optuna_search.fit(train_X, train_y)

Collecting optuna-integration[sklearn]
  Downloading optuna_integration-4.8.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[sklearn]) (4.8.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from optuna-integration[sklearn]) (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from optuna-integration[sklearn]) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from optuna-integration[sklearn]) (1.16.3)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[sklearn]) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[sklearn]) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[sklearn]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[sklearn]) (26.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[sklearn]) (2.0.49)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[sklearn]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[sklearn]) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->optuna-integration[sklearn]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->optuna-integration[sklearn]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->optuna-integration[sklearn]) (2026.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->optuna-integration[sklearn]) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->optuna-integration[sklearn]) (3.6.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[sklearn]) (1.3.11)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[sklearn]) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->optuna-integration[sklearn]) (1.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[sklearn]) (3.4.0)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[sklearn]) (3.0.3)
Downloading optuna_integration-4.8.0-py3-none-any.whl (103 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.2/103.2 kB 2.0 MB/s eta 0:00:00 0:00:01
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.8.0

/tmp/ipykernel_1114/818243538.py:2: ExperimentalWarning:

OptunaSearchCV is experimental (supported from v0.17.0). The interface can change in the future.

[I 2026-05-04 13:54:14,761] A new study created in memory with name: no-name-49b00a59-306b-48c9-8dcb-b986c6894af2
INFO:optuna_integration.sklearn.sklearn:Searching the best hyperparameters using 28974 samples...
[I 2026-05-04 13:54:52,985] Trial 0 finished with value: -0.043575830374827526 and parameters: {'regressor__alpha': 0.011755306512167085, 'regressor__l1_ratio': 0.2719440250451275}. Best is trial 0 with value: -0.043575830374827526.
[I 2026-05-04 13:54:56,348] Trial 1 finished with value: -0.04490805542451172 and parameters: {'regressor__alpha': 0.314899968694659, 'regressor__l1_ratio': 0.5954673738469047}. Best is trial 0 with value: -0.043575830374827526.
[I 2026-05-04 13:54:58,447] Trial 2 finished with value: -0.04764561259251259 and parameters: {'regressor__alpha': 0.7881846443184801, 'regressor__l1_ratio': 0.25942048086588704}. Best is trial 0 with value: -0.043575830374827526.
[I 2026-05-04 13:55:00,572] Trial 3 finished with value: -0.04761136120972595 and parameters: {'regressor__alpha': 0.724862351977224, 'regressor__l1_ratio': 0.1943131580535695}. Best is trial 0 with value: -0.043575830374827526.
[I 2026-05-04 13:55:03,415] Trial 4 finished with value: -0.04657848422879558 and parameters: {'regressor__alpha': 0.7809021399195833, 'regressor__l1_ratio': 0.5342367924272827}. Best is trial 0 with value: -0.043575830374827526.
[I 2026-05-04 13:55:05,609] Trial 5 finished with value: -0.04742652193012782 and parameters: {'regressor__alpha': 0.8588777363297035, 'regressor__l1_ratio': 0.3856626946468638}. Best is trial 0 with value: -0.043575830374827526.
[I 2026-05-04 13:55:08,580] Trial 6 finished with value: -0.045274310508974014 and parameters: {'regressor__alpha': 0.6297819721388296, 'regressor__l1_ratio': 0.7757861355071872}. Best is trial 0 with value: -0.043575830374827526.
[I 2026-05-04 13:55:10,573] Trial 7 finished with value: -0.048088201038949105 and parameters: {'regressor__alpha': 0.8378068178082401, 'regressor__l1_ratio': 0.19163029233165274}. Best is trial 0 with value: -0.043575830374827526.
[I 2026-05-04 13:55:14,066] Trial 8 finished with value: -0.045138425850800155 and parameters: {'regressor__alpha': 0.38994125610570013, 'regressor__l1_ratio': 0.6067422657781192}. Best is trial 0 with value: -0.043575830374827526.
[I 2026-05-04 13:55:17,962] Trial 9 finished with value: -0.04531722827857816 and parameters: {'regressor__alpha': 0.4359785845924496, 'regressor__l1_ratio': 0.5947778448942151}. Best is trial 0 with value: -0.043575830374827526.
INFO:optuna_integration.sklearn.sklearn:Finished hyperparameter search!
INFO:optuna_integration.sklearn.sklearn:Refitting the estimator using 28974 samples...
INFO:optuna_integration.sklearn.sklearn:Finished refitting! (elapsed time: 10.909 sec.)

OptunaSearchCV(estimator=Pipeline(steps=[('preprocessor',
                                          ColumnTransformer(transformers=[('num',
                                                                           StandardScaler(),
                                                                           ['battery-capacity',
                                                                            'charge-time',
                                                                            'compression',
                                                                            'consumption-mixed',
                                                                            'cylinders-value',
                                                                            'luxury',
                                                                            'max-speed',
                                                                            'power-electro-kw',
                                                                            'valves',
                                                                            'weight',
                                                                            'configurations_auto-premiere',
                                                                            'configurations_back-wheel-base',
                                                                            'configurations_tank-volume']...
                                                                            'models_country-from',
                                                                            'models_group',
                                                                            'models_light-and-commercial',
                                                                            'models_male'])])),
                                         ('regressor', ElasticNet())]),
               n_jobs=1,
               param_distributions={'regressor__alpha': FloatDistribution(high=1.0, log=False, low=0.01, step=None),
                                    'regressor__l1_ratio': FloatDistribution(high=1.0, log=False, low=0.01, step=None)},
               scoring='neg_mean_absolute_percentage_error', timeout=600,
               verbose=2)

In [47]:
print("Best trial:")
trial = optuna_search.study_.best_trial
print("  Value: ", trial.value)

Best trial:
  Value:  -0.043575830374827526

In [48]:
print("  Params: ")
for key, value in trial.params.items():
        print("    {}: {}".format(key, value))

  Params:
    regressor__alpha: 0.011755306512167085
    regressor__l1_ratio: 0.2719440250451275

In [49]:
pred_test_opt = optuna_search.predict(test_X)

In [50]:
mean_absolute_percentage_error(test_y, pred_test_opt)

0.04410431452889491

**Задание**

Изучить https://optuna.readthedocs.io/en/stable/tutorial/index.html.
Рализовать выбор лучшей модели с помощью библиотеки optune.
Оптимизатор должен за 100 шагов:
- выбрать лучший способ стандартизации количественных признаков;
- выбрать лучшую модель линейной регрессии;
- подобрать гиперпараметры модели.

Вывести подобранные величины.

In [51]:
regression_name = trial.suggest_categorical('regression', ['Lasso', 'Ridge', 'ElasticNet'])

ValueError: The value of the parameter 'regression' is not found. Please set it at the construction of the FrozenTrial object.

In [54]:
def objective(trial):


    scale_name = trial.suggest_categorical('scale', ['StandardScaler', 'RobustScaler', 'MinMaxScaler'])

    if scale_name == 'StandardScaler':
        scaler = StandardScaler()
    elif scale_name == 'RobustScaler':
        scaler = RobustScaler()
    else:
        scaler = MinMaxScaler()
    
    x, y = scaler.fit_transform(train_X), train_y

    regression_name = trial.suggest_categorical('regression', ['Lasso', 'Ridge', 'ElasticNet', 'LinearRegression'])
    if regression_name == "Lasso":
        alpha = trial.suggest_float("alpha", 0, 1)
        regression_obj = Lasso(alpha=alpha)
    elif regression_name == "Ridge":
        alpha = trial.suggest_float("alpha", 0, 1)
        regression_obj = Ridge(alpha=alpha)
    elif regression_name == 'LinearRegression':
        regression_obj = LinearRegression()
    else:
        alpha = trial.suggest_float("alpha", 0, 1)
        l1_ratio = trial.suggest_float("l1_ratio", 0, 1)
        regression_obj = ElasticNet(alpha=alpha, l1_ratio=l1_ratio)

    score = sklearn.model_selection.cross_val_score(regression_obj, x, y, n_jobs=-1, cv=5, scoring='r2')
    accuracy = score.mean()
    return accuracy


if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)
    print(study.best_trial)

[I 2026-05-04 13:57:29,435] A new study created in memory with name: no-name-0295e0a8-23da-4794-a44f-40872f2c0238

[I 2026-05-04 13:57:29,791] Trial 0 finished with value: 0.4540477568161424 and parameters: {'scale': 'StandardScaler', 'regression': 'Lasso', 'alpha': 0.5466274518795519}. Best is trial 0 with value: 0.4540477568161424.
[I 2026-05-04 13:57:30,425] Trial 1 finished with value: 0.4540855548813907 and parameters: {'scale': 'StandardScaler', 'regression': 'Lasso', 'alpha': 0.22823927173433212}. Best is trial 1 with value: 0.4540855548813907.
[I 2026-05-04 13:57:30,878] Trial 2 finished with value: 0.4520050488522429 and parameters: {'scale': 'RobustScaler', 'regression': 'Lasso', 'alpha': 0.9963013907055127}. Best is trial 1 with value: 0.4540855548813907.
[I 2026-05-04 13:57:31,112] Trial 3 finished with value: 0.06663525694417624 and parameters: {'scale': 'MinMaxScaler', 'regression': 'ElasticNet', 'alpha': 0.898383517278058, 'l1_ratio': 0.09621372122018634}. Best is trial 1 with value: 0.4540855548813907.
[I 2026-05-04 13:57:31,223] Trial 4 finished with value: 0.45415419754499686 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.43530616561764657}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:31,386] Trial 5 finished with value: 0.45409051727894195 and parameters: {'scale': 'MinMaxScaler', 'regression': 'LinearRegression'}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:31,907] Trial 6 finished with value: 0.4075251005816322 and parameters: {'scale': 'RobustScaler', 'regression': 'ElasticNet', 'alpha': 0.5008365067538401, 'l1_ratio': 0.3408090163616784}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:32,255] Trial 7 finished with value: 0.45398274572581154 and parameters: {'scale': 'StandardScaler', 'regression': 'Lasso', 'alpha': 0.6864613664080381}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:32,535] Trial 8 finished with value: 0.43524263866776225 and parameters: {'scale': 'StandardScaler', 'regression': 'ElasticNet', 'alpha': 0.5162091453039623, 'l1_ratio': 0.49221691805111134}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:34,104] Trial 9 finished with value: 0.45414198612271395 and parameters: {'scale': 'MinMaxScaler', 'regression': 'ElasticNet', 'alpha': 0.0011250248757815884, 'l1_ratio': 0.9750549666191747}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:34,321] Trial 10 finished with value: 0.4541438639625525 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.23728910389676916}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:34,540] Trial 11 finished with value: 0.454144682695345 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.24425860837272845}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:34,667] Trial 12 finished with value: 0.4541442134582992 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.24022584225277777}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:34,890] Trial 13 finished with value: 0.4541524230595938 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.3406600846759944}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:35,127] Trial 14 finished with value: 0.4541533937866916 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.3650001404366136}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:35,342] Trial 15 finished with value: 0.45412887173505706 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.7471419512580988}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:35,553] Trial 16 finished with value: 0.45409051727894206 and parameters: {'scale': 'RobustScaler', 'regression': 'LinearRegression'}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:35,692] Trial 17 finished with value: 0.4541528750729188 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.3508551633086548}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:35,920] Trial 18 finished with value: 0.4541149155714973 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.08129653193561082}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:36,185] Trial 19 finished with value: 0.4540939755589929 and parameters: {'scale': 'RobustScaler', 'regression': 'Ridge', 'alpha': 0.3870815726955376}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:36,359] Trial 20 finished with value: 0.45409051727894195 and parameters: {'scale': 'MinMaxScaler', 'regression': 'LinearRegression'}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:36,573] Trial 21 finished with value: 0.454154093830285 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.3953206883386465}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:36,802] Trial 22 finished with value: 0.45413890564639364 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.669463076088177}. Best is trial 4 with value: 0.45415419754499686.
[I 2026-05-04 13:57:37,015] Trial 23 finished with value: 0.45415423399750915 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.4093888910373291}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:37,252] Trial 24 finished with value: 0.4541541046799763 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.443800733389774}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:37,433] Trial 25 finished with value: 0.4541464373598127 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.5946271943792137}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:37,717] Trial 26 finished with value: 0.45415390630112384 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.455843340301953}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:38,014] Trial 27 finished with value: 0.45414545268609635 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.6058403268570549}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:38,430] Trial 28 finished with value: 0.45409051727894206 and parameters: {'scale': 'RobustScaler', 'regression': 'LinearRegression'}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:38,902] Trial 29 finished with value: 0.45407658133641393 and parameters: {'scale': 'StandardScaler', 'regression': 'Lasso', 'alpha': 0.4545934976756661}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:39,072] Trial 30 finished with value: 0.4540909582310341 and parameters: {'scale': 'StandardScaler', 'regression': 'Ridge', 'alpha': 0.18401888663878158}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:39,277] Trial 31 finished with value: 0.45415419556252096 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.43553463877269816}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:39,578] Trial 32 finished with value: 0.4541540625950766 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.4467965744556581}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:39,807] Trial 33 finished with value: 0.45415205763018884 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.33334411800270874}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:40,034] Trial 34 finished with value: 0.44241658585634697 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Lasso', 'alpha': 0.5809386862443792}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:40,151] Trial 35 finished with value: 0.4541497882563865 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.297920897373618}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:40,461] Trial 36 finished with value: 0.42163109970838103 and parameters: {'scale': 'MinMaxScaler', 'regression': 'ElasticNet', 'alpha': 0.434889158341841, 'l1_ratio': 0.9889133051497956}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:40,928] Trial 37 finished with value: 0.45265677165414536 and parameters: {'scale': 'RobustScaler', 'regression': 'Lasso', 'alpha': 0.5409158306263709}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:41,148] Trial 38 finished with value: 0.45409086280910466 and parameters: {'scale': 'StandardScaler', 'regression': 'Ridge', 'alpha': 0.1441060296896834}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:41,420] Trial 39 finished with value: 0.45409051727894195 and parameters: {'scale': 'MinMaxScaler', 'regression': 'LinearRegression'}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:41,667] Trial 40 finished with value: 0.25437660056357947 and parameters: {'scale': 'MinMaxScaler', 'regression': 'ElasticNet', 'alpha': 0.2949371742292406, 'l1_ratio': 0.7133407382106401}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:41,782] Trial 41 finished with value: 0.4541541857322451 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.40312445616571857}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:42,008] Trial 42 finished with value: 0.45415297393317466 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.48882542354336517}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:42,134] Trial 43 finished with value: 0.4541542095203641 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.4058516688063872}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:42,251] Trial 44 finished with value: 0.45415166349607594 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.5185776354925109}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:42,379] Trial 45 finished with value: 0.45409149000300825 and parameters: {'scale': 'StandardScaler', 'regression': 'Ridge', 'alpha': 0.4073774600420781}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:42,494] Trial 46 finished with value: 0.4541495396183034 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.29469861442001893}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:42,741] Trial 47 finished with value: 0.08393608308568805 and parameters: {'scale': 'MinMaxScaler', 'regression': 'ElasticNet', 'alpha': 0.644540244885084, 'l1_ratio': 0.05884884789979472}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:42,889] Trial 48 finished with value: 0.45409487915460645 and parameters: {'scale': 'RobustScaler', 'regression': 'Ridge', 'alpha': 0.4951959104232819}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:43,128] Trial 49 finished with value: 0.43955206575082 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Lasso', 'alpha': 0.7255837399209593}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:43,343] Trial 50 finished with value: 0.454105465569806 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.889531883125539}. Best is trial 23 with value: 0.45415423399750915.
[I 2026-05-04 13:57:43,583] Trial 51 finished with value: 0.4541542646380693 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.41980803014031187}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:43,810] Trial 52 finished with value: 0.45415417658523216 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.40218923648352584}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:44,026] Trial 53 finished with value: 0.45415236668640724 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.33948487444301767}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:44,252] Trial 54 finished with value: 0.4541495206845732 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.5544776649256051}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:44,367] Trial 55 finished with value: 0.454147181676735 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.2678262036757043}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:44,602] Trial 56 finished with value: 0.45415291395658014 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.49044188683753287}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:44,878] Trial 57 finished with value: 0.45409051727894195 and parameters: {'scale': 'MinMaxScaler', 'regression': 'LinearRegression'}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:44,995] Trial 58 finished with value: 0.45415383471948234 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.38112015681807304}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:45,248] Trial 59 finished with value: 0.4540942428621243 and parameters: {'scale': 'RobustScaler', 'regression': 'Ridge', 'alpha': 0.4187332300422944}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:45,468] Trial 60 finished with value: 0.4541395366614694 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.20471194959092018}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:45,607] Trial 61 finished with value: 0.4541539809059838 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.3883129397943306}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:45,734] Trial 62 finished with value: 0.45415309590043584 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.35646932073566806}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:45,964] Trial 63 finished with value: 0.4541536199669383 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.46831074007859186}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:46,085] Trial 64 finished with value: 0.45415426093899647 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.416173017711979}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:46,214] Trial 65 finished with value: 0.4540912756873812 and parameters: {'scale': 'StandardScaler', 'regression': 'Ridge', 'alpha': 0.31716868952775046}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:46,459] Trial 66 finished with value: 0.2112282326743154 and parameters: {'scale': 'MinMaxScaler', 'regression': 'ElasticNet', 'alpha': 0.5242554716803242, 'l1_ratio': 0.7558317902579224}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:46,576] Trial 67 finished with value: 0.4541542626579723 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.422450931032646}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:46,811] Trial 68 finished with value: 0.454154179299825 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.4372980206364683}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:46,986] Trial 69 finished with value: 0.45409051727894195 and parameters: {'scale': 'MinMaxScaler', 'regression': 'LinearRegression'}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:47,304] Trial 70 finished with value: 0.4442653715257636 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Lasso', 'alpha': 0.4729822508415589}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:47,521] Trial 71 finished with value: 0.4541532473475713 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.36064476688240715}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:47,762] Trial 72 finished with value: 0.45415426343712995 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.4177306476902542}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:47,979] Trial 73 finished with value: 0.4541494264899155 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.5558577803962403}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:48,204] Trial 74 finished with value: 0.4541534648057799 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.3672486563135453}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:48,322] Trial 75 finished with value: 0.4541542282214498 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.431209928326333}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:48,473] Trial 76 finished with value: 0.45409428753025927 and parameters: {'scale': 'RobustScaler', 'regression': 'Ridge', 'alpha': 0.42404910710832106}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:48,697] Trial 77 finished with value: 0.45414652243199694 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.261218416249707}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:48,919] Trial 78 finished with value: 0.45409130284413124 and parameters: {'scale': 'StandardScaler', 'regression': 'Ridge', 'alpha': 0.3285851194682534}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:49,136] Trial 79 finished with value: 0.4541536399571173 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.46754265162541353}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:49,374] Trial 80 finished with value: 0.12199873160993291 and parameters: {'scale': 'MinMaxScaler', 'regression': 'ElasticNet', 'alpha': 0.5062789956278961, 'l1_ratio': 0.30315690410534035}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:49,589] Trial 81 finished with value: 0.4541541872073493 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.43646359791758843}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:49,800] Trial 82 finished with value: 0.45415375130678043 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.37757648902944496}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:50,095] Trial 83 finished with value: 0.45415426279890525 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.42235463062372947}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:50,300] Trial 84 finished with value: 0.45415426426917893 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.41865088300015063}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:50,502] Trial 85 finished with value: 0.4541542556290782 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.41414530139379624}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:50,699] Trial 86 finished with value: 0.45415372105221674 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.4642963867151649}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:51,005] Trial 87 finished with value: 0.4541503838147789 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.30605078997671753}. Best is trial 51 with value: 0.4541542646380693.
[I 2026-05-04 13:57:51,415] Trial 88 finished with value: 0.445069466535528 and parameters: {'scale': 'MinMaxScaler', 'regression': 'Lasso', 'alpha': 0.4169215700873832}. Best is trial 51 with value: 0.4541542646380693.

FrozenTrial(number=51, state=<TrialState.COMPLETE: 1>, values=[0.4541542646380693], datetime_start=datetime.datetime(2026, 5, 4, 13, 57, 43, 344914), datetime_complete=datetime.datetime(2026, 5, 4, 13, 57, 43, 583444), params={'scale': 'MinMaxScaler', 'regression': 'Ridge', 'alpha': 0.41980803014031187}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'scale': CategoricalDistribution(choices=('StandardScaler', 'RobustScaler', 'MinMaxScaler')), 'regression': CategoricalDistribution(choices=('Lasso', 'Ridge', 'ElasticNet', 'LinearRegression')), 'alpha': FloatDistribution(high=1.0, log=False, low=0.0, step=None)}, trial_id=51, value=None)

In [53]:
# value: 0.4538629185314214 and parameters: {'scale': 'StandardScaler', 'regression': 'Ridge', 'alpha': 3.455322262964176}